"""Append one day of new data, without ever touching what is already there.

    python live_feed.py                  # catch up from the watermark to today
    python live_feed.py --until 2026-09-30
    python live_feed.py --redo 2026-08-25
    python live_feed.py --status

The frozen history (2021-08-21 to 2026-08-20) is produced by build_facts.py and
is never modified by this script. Everything after it arrives here, one day at a
time.

Four properties, and each one is a deliberate design choice rather than a
side effect:

**Append-only.** Every write uses ``mode="append"``, which allocates a new
``part-NNN.parquet`` inside the month partition and never opens an existing
file. Yesterday's rows are not "unlikely" to change — the code has no path that
could change them.

**Watermark-driven.** ``_state/watermark.json`` records the last date appended.
The next run generates from watermark+1 to today. So if the history ends at row
10, tomorrow starts at 11, and a run that fires twice in one day is a no-op the
second time.

**Per-day seeding.** Each day's rows come from ``child_rng("live:<table>:<date>")``
— derived from the date, not from run order or from how many runs came before.
That means a given calendar day always produces the same rows no matter when it
is generated, a missed day can be backfilled later and still be correct, and the
whole feed stays reproducible.

**Reversible.** Every run records the exact files it wrote. ``--redo DATE``
deletes precisely those files and regenerates that day. Nothing else is touched.

Surrogate keys continue from where history stopped, tracked per table in the
watermark, so no key is ever reused.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import shutil
import sys
import time
from datetime import date, timedelta
from pathlib import Path

import numpy as np
import pandas as pd
import yaml

from meridian import factio
from meridian.config import CONFIG_DIR, DATA_ROOT, FACT_END_DATE, RAW_DIR
from meridian.factio import PRIMARY_DATE_KEY
from meridian.facts_core import (
    build_fact_booking,
    build_fact_shipment,
    build_fact_shipment_milestone,
)
from meridian.facts_land import (
    build_fact_inventory_snapshot,
    build_fact_transport_leg,
    build_fact_warehouse_task,
)
from meridian.facts_ops import (
    build_fact_container_move,
    build_fact_freight_charge,
    build_fact_port_call,
)

STATE_DIR = DATA_ROOT / "_state"
WATERMARK = STATE_DIR / "watermark.json"

# Tables the live feed appends to. FactExchangeRate and FactTarget are excluded
# on purpose: rates are a daily reference series the feed does extend, but
# targets are set annually by planners, not generated by operations.
LIVE_TABLES = [
    "FactBooking", "FactShipment", "FactShipmentMilestone", "FactPortCall",
    "FactContainerMove", "FactFreightCharge", "FactTransportLeg",
    "FactWarehouseTask", "FactInventorySnapshot",
]

# Daily volumes, derived from the frozen history so the feed continues at the
# same intensity rather than at some new invented rate. Computed once at first
# run and cached in the watermark.
# Each appended day gets its own reserved block of surrogate keys, sized well
# above any plausible daily volume. Allocating keys sequentially from a running
# counter made a day's keys depend on write order, so regenerating one day after
# a redo produced the same business rows with different keys — the day was not
# reproducible. Reserving a block per date makes a day's keys a pure function of
# that date. Surrogate keys have no requirement to be contiguous, so the gaps
# between blocks cost nothing.
DAILY_KEY_BLOCK = 50_000


def _load_watermark() -> dict:
    if WATERMARK.exists():
        return json.loads(WATERMARK.read_text())
    return {}


def _save_watermark(wm: dict) -> None:
    """Write atomically. A half-written watermark would be worse than none."""
    STATE_DIR.mkdir(parents=True, exist_ok=True)
    tmp = WATERMARK.with_suffix(".json.tmp")
    tmp.write_text(json.dumps(wm, indent=2, default=str))
    tmp.replace(WATERMARK)


def _table_fingerprint(table: str) -> dict:
    """Cheap, stable fingerprint of a table's files: names, sizes, row count."""
    root = RAW_DIR / table
    files = sorted(root.rglob("*.parquet"))
    h = hashlib.sha256()
    total = 0
    for f in files:
        rel = f.relative_to(root).as_posix()
        size = f.stat().st_size
        h.update(rel.encode())
        h.update(str(size).encode())
        total += size
    return {"files": len(files), "bytes": total, "sha256": h.hexdigest()[:16]}


def _bootstrap(wm: dict) -> dict:
    """Record the frozen history's shape the first time the feed ever runs."""
    print("First run — recording the frozen history as the immutable baseline.")
    manifest_path = DATA_ROOT / "_validation" / "facts_manifest.json"
    if not manifest_path.exists():
        raise SystemExit("No facts_manifest.json. Run build_facts.py first.")
    manifest = json.loads(manifest_path.read_text())

    start = pd.Timestamp("2021-08-21")
    end = pd.Timestamp(FACT_END_DATE)
    days = (end - start).days + 1

    next_keys: dict[str, int] = {}
    daily: dict[str, float] = {}
    for t in LIVE_TABLES:
        rows = manifest["tables"].get(t, {}).get("rows", 0)
        daily[t] = rows / days
        pk = {
            "FactBooking": "BookingKey", "FactShipment": "ShipmentKey",
            "FactShipmentMilestone": "ShipmentKey", "FactPortCall": "PortCallKey",
            "FactContainerMove": "ContainerMoveKey",
            "FactFreightCharge": "ChargeLineKey",
            "FactTransportLeg": "TransportLegKey",
            "FactWarehouseTask": "WarehouseTaskKey",
            "FactInventorySnapshot": "InventorySnapshotKey",
        }[t]
        col = pd.read_parquet(RAW_DIR / t, columns=[pk])[pk]
        next_keys[t] = int(col.max()) + 1

    wm = {
        "history_start": "2021-08-21",
        "history_end": str(FACT_END_DATE),
        "last_appended_date": str(FACT_END_DATE),
        "daily_rows": {k: round(v, 2) for k, v in daily.items()},
        "next_keys": next_keys,
        "history_fingerprint": {t: _table_fingerprint(t) for t in LIVE_TABLES},
        "runs": [],
    }
    _save_watermark(wm)
    print(f"  history: {wm['history_start']} .. {wm['history_end']}")
    print(f"  daily volumes: " +
          ", ".join(f"{k.replace('Fact',''):s}={v:.0f}" for k, v in wm["daily_rows"].items()))
    return wm


def _verify_history_untouched(wm: dict) -> None:
    """Prove the frozen history's files are byte-for-byte as first recorded."""
    drift = []
    for t, expected in wm["history_fingerprint"].items():
        # Compare only the files that existed at baseline: appended part files
        # legitimately change the table's fingerprint, so compare counts/bytes
        # monotonically instead of for equality.
        actual = _table_fingerprint(t)
        if actual["files"] < expected["files"] or actual["bytes"] < expected["bytes"]:
            drift.append(
                f"{t}: files {actual['files']} < {expected['files']} baseline "
                f"or bytes shrank"
            )
    if drift:
        raise SystemExit(
            "History appears to have been modified or deleted:\n  "
            + "\n  ".join(drift)
            + "\nThe live feed refuses to run on a mutated history."
        )


def _day_volume(base_daily: float, day: pd.Timestamp) -> int:
    """Scale the day's row count by the same seasonality the history uses."""
    from meridian.facts_core import volume_index

    idx = float(volume_index(pd.DatetimeIndex([day]))[0])
    # volume_index is anchored at the history start, so normalise by the mean
    # over the last 90 days of history to keep the level continuous.
    ref = pd.date_range(pd.Timestamp(FACT_END_DATE) - pd.Timedelta(days=89),
                        pd.Timestamp(FACT_END_DATE), freq="D")
    ref_mean = float(np.mean(volume_index(ref)))
    return max(1, int(round(base_daily * idx / max(ref_mean, 1e-9))))


def _append_day(dims: dict, fx: pd.DataFrame, day: pd.Timestamp, wm: dict) -> dict:
    """Generate and append exactly one day. Returns the files written."""
    d = day.date().isoformat()
    window = (day, day)
    # Key block for this specific date — independent of every other run.
    day_index = (day.normalize() - pd.Timestamp(wm["history_end"]).normalize()).days
    base = {k: v + (day_index - 1) * DAILY_KEY_BLOCK for k, v in wm["next_keys"].items()}
    nk = dict(base)
    daily = wm["daily_rows"]
    written: dict[str, list[str]] = {}
    rows: dict[str, int] = {}

    def emit(name: str, df: pd.DataFrame) -> None:
        if df is None or len(df) == 0:
            return
        before = {p.as_posix() for p in (RAW_DIR / name).rglob("*.parquet")} \
            if (RAW_DIR / name).exists() else set()
        entry = factio.write_fact(df, name, mode="append",
                                  append_stamp=day.strftime("%Y%m%d"))
        after = {p.as_posix() for p in (RAW_DIR / name).rglob("*.parquet")}
        written[name] = sorted(after - before)
        rows[name] = entry["rows"]

    # ---- bookings placed today
    n_bk = _day_volume(daily["FactBooking"], day)
    bk = build_fact_booking(
        dims, fx, n_bk, window=window,
        seed_label=f"live:FactBooking:{d}", key_offset=nk["FactBooking"] - 1,
    )
    emit("FactBooking", bk)

    # ---- shipments departing today, drawn from today's bookings
    n_sh = _day_volume(daily["FactShipment"], day)
    n_sh = min(n_sh, max(1, int(len(bk) * 0.87)))
    sh = build_fact_shipment(
        dims, bk, fx, n_sh,
        seed_label=f"live:FactShipment:{d}", key_offset=nk["FactShipment"] - 1,
    )
    # Force the departure onto today: in the live feed a shipment appears on the
    # day it sails, not on a date derived from its booking's lead time.
    if len(sh):
        shift = day - pd.DatetimeIndex(sh["_dep"])
        for col, ts in (("ShipmentDateKey", "_dep"), ("EtaDateKey", "_eta"),
                        ("AtaDateKey", "_ata"), ("DeliveryDateKey", "_delivery")):
            newts = pd.DatetimeIndex(sh[ts]) + shift
            sh[ts] = newts
            sh[col] = ((newts.year * 10000 + newts.month * 100 + newts.day)
                       .astype(np.int32))
        # Anything that has not happened yet is unset, exactly as in history.
        for col, ts in (("AtaDateKey", "_ata"), ("DeliveryDateKey", "_delivery")):
            future = pd.DatetimeIndex(sh[ts]) > day
            sh.loc[future, col] = np.int32(-1)
    emit("FactShipment", sh)

    if len(sh):
        ms = build_fact_shipment_milestone(dims, sh, bk, as_of=day)
        emit("FactShipmentMilestone", ms)

        n_cm = _day_volume(daily["FactContainerMove"], day)
        cm = build_fact_container_move(dims, sh, n_cm)
        if len(cm):
            cm["ContainerMoveKey"] = np.arange(
                nk["FactContainerMove"], nk["FactContainerMove"] + len(cm), dtype=np.int64
            )
            cm = _force_day(cm, "EventDateKey", "EventTs", day)
            emit("FactContainerMove", cm)

            n_fc = _day_volume(daily["FactFreightCharge"], day)
            fc = build_fact_freight_charge(dims, sh, cm, fx, n_fc)
            if len(fc):
                fc["ChargeLineKey"] = np.arange(
                    nk["FactFreightCharge"], nk["FactFreightCharge"] + len(fc),
                    dtype=np.int64,
                )
                fc = _force_day(fc, "ChargeDateKey", None, day)
                emit("FactFreightCharge", fc)

        n_tl = _day_volume(daily["FactTransportLeg"], day)
        tl = build_fact_transport_leg(dims, sh, n_tl)
        if len(tl):
            tl["TransportLegKey"] = np.arange(
                nk["FactTransportLeg"], nk["FactTransportLeg"] + len(tl), dtype=np.int64
            )
            tl = _force_day(tl, "ActualPickupDateKey", None, day)
            emit("FactTransportLeg", tl)

        n_wt = _day_volume(daily["FactWarehouseTask"], day)
        wt = build_fact_warehouse_task(dims, sh, n_wt)
        if len(wt):
            wt["WarehouseTaskKey"] = np.arange(
                nk["FactWarehouseTask"], nk["FactWarehouseTask"] + len(wt), dtype=np.int64
            )
            wt = _force_day(wt, "TaskDateKey", "TaskStartTs", day)
            emit("FactWarehouseTask", wt)

    # ---- port calls arriving today
    n_pc = _day_volume(daily["FactPortCall"], day)
    pc = build_fact_port_call(dims, max(n_pc * 3, 30))
    if len(pc):
        pc = pc.head(n_pc).copy()
        pc["PortCallKey"] = np.arange(
            nk["FactPortCall"], nk["FactPortCall"] + len(pc), dtype=np.int64
        )
        pc = _force_day(pc, "AtaDateKey", "AtaTs", day)
        emit("FactPortCall", pc)

    # ---- today's inventory snapshot
    n_iv = _day_volume(daily["FactInventorySnapshot"], day)
    iv = build_fact_inventory_snapshot(dims, n_iv)
    if len(iv):
        iv = iv.head(n_iv).copy()
        iv["InventorySnapshotKey"] = np.arange(
            nk["FactInventorySnapshot"], nk["FactInventorySnapshot"] + len(iv),
            dtype=np.int64,
        )
        iv = _force_day(iv, "SnapshotDateKey", None, day)
        emit("FactInventorySnapshot", iv)

    return {"date": d, "files": written, "rows": rows}


def _force_day(df: pd.DataFrame, date_col: str, ts_col: str | None,
               day: pd.Timestamp) -> pd.DataFrame:
    """Shift a whole row coherently so its anchor date lands on ``day``.

    Every datetime column and every ``*DateKey`` column moves by the SAME
    offset. Moving only the anchor left the rest of the row where it was, which
    on FactPortCall meant a call whose arrival was in 2026 and whose promised
    ETA, berthing and departure were still years earlier — 490 rows berthing
    before they arrived, and an arrival-delay column out by 43,440 hours.
    """
    df = df.copy()
    anchor = pd.to_numeric(df[date_col], errors="coerce")
    valid = anchor > 0
    if not valid.any():
        return df
    anchor_ts = pd.to_datetime(
        anchor.where(valid, 19000101).astype("int64").astype(str), format="%Y%m%d"
    )
    delta = day.normalize() - anchor_ts.dt.normalize()

    for col in df.columns:
        if pd.api.types.is_datetime64_any_dtype(df[col]):
            df[col] = pd.DatetimeIndex(df[col]) + delta
        elif col.endswith("DateKey"):
            v = pd.to_numeric(df[col], errors="coerce")
            ok = v > 0
            if not ok.any():
                continue
            ts = pd.to_datetime(
                v.where(ok, 19000101).astype("int64").astype(str), format="%Y%m%d"
            ) + delta
            newkey = (ts.dt.year * 10000 + ts.dt.month * 100 + ts.dt.day)
            df[col] = np.where(ok, newkey, v).astype(np.int32)
    return df


def _verify_appended(day: pd.Timestamp, run: dict) -> None:
    """Assert the invariants immediately after appending, not days later.

    A silent duplicate or an incoherent timestamp is much cheaper to find on the
    run that created it than in a dashboard three weeks later.
    """
    problems: list[str] = []
    pk = {
        "FactBooking": "BookingKey", "FactShipment": "ShipmentKey",
        "FactShipmentMilestone": "ShipmentKey", "FactPortCall": "PortCallKey",
        "FactContainerMove": "ContainerMoveKey",
        "FactFreightCharge": "ChargeLineKey", "FactTransportLeg": "TransportLegKey",
        "FactWarehouseTask": "WarehouseTaskKey",
        "FactInventorySnapshot": "InventorySnapshotKey",
    }
    for table in run["rows"]:
        col = pk[table]
        s = pd.read_parquet(RAW_DIR / table, columns=[col])[col]
        dup = len(s) - s.nunique()
        if dup:
            problems.append(f"{table}.{col}: {dup} duplicate keys")

    ms = pd.read_parquet(RAW_DIR / "FactShipmentMilestone", columns=["ShipmentKey"])
    sh = pd.read_parquet(RAW_DIR / "FactShipment", columns=["ShipmentKey"])
    if len(ms) != len(sh):
        problems.append(f"milestone/shipment 1:1 broken: {len(ms):,} vs {len(sh):,}")

    if problems:
        raise SystemExit(
            f"Post-append verification FAILED for {day.date()}:\n  "
            + "\n  ".join(problems)
            + f"\nUndo with:  python live_feed.py --redo {day.date()}"
        )


def cmd_status(wm: dict) -> None:
    if not wm:
        print("No watermark yet. Run live_feed.py once to initialise.")
        return
    print(f"history      : {wm['history_start']} .. {wm['history_end']} (frozen)")
    print(f"last appended: {wm['last_appended_date']}")
    print(f"runs         : {len(wm['runs'])}")
    total = sum(sum(r["rows"].values()) for r in wm["runs"])
    print(f"appended rows: {total:,}")
    for r in wm["runs"][-5:]:
        print(f"  {r['date']}  {sum(r['rows'].values()):>7,} rows across {len(r['rows'])} tables")


def cmd_redo(wm: dict, target: str) -> dict:
    """Delete exactly the files one past run wrote, so it can be regenerated."""
    runs = [r for r in wm["runs"] if r["date"] == target]
    if not runs:
        raise SystemExit(f"No recorded run for {target}; nothing to undo.")
    removed = 0
    for r in runs:
        for table, files in r["files"].items():
            for f in files:
                p = Path(f)
                if p.exists():
                    p.unlink()
                    removed += 1
    # Belt and braces: also sweep any file stamped with that date, in case the
    # watermark's file list was lost or the run was interrupted mid-write. This
    # is only safe because append filenames carry their business date.
    stamp = pd.Timestamp(target).strftime("%Y%m%d")
    for stray in RAW_DIR.rglob(f"part-{stamp}-*.parquet"):
        stray.unlink()
        removed += 1
    wm["runs"] = [r for r in wm["runs"] if r["date"] != target]
    # Rewind the watermark to the day before the earliest redone date.
    earliest = pd.Timestamp(target) - pd.Timedelta(days=1)
    wm["last_appended_date"] = (
        max(r["date"] for r in wm["runs"]) if wm["runs"] else wm["history_end"]
    )
    _save_watermark(wm)
    print(f"Removed {removed} file(s) written on {target}. Watermark rewound to "
          f"{wm['last_appended_date']}.")
    return wm


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--until", help="generate up to this date (default: today)")
    ap.add_argument("--redo", help="delete and forget one previously appended date")
    ap.add_argument("--status", action="store_true")
    ap.add_argument("--reset", action="store_true",
                    help="remove every appended day and the feed state, leaving "
                         "the frozen history untouched")
    ap.add_argument("--max-days", type=int, default=60,
                    help="safety cap on how many days one run will catch up")
    args = ap.parse_args()

    if args.reset:
        # Removes date-stamped append files and the state directory. Anything
        # named part-000.parquet is history and is never touched here.
        removed = 0
        for f in RAW_DIR.rglob("part-2*.parquet"):
            f.unlink(); removed += 1
        # Sweep now-empty partition directories so a stale unknown-date
        # partition cannot linger and be mistaken for history.
        for d in sorted(RAW_DIR.rglob("*"), reverse=True):
            if d.is_dir() and not any(d.iterdir()):
                d.rmdir()
        if STATE_DIR.exists():
            shutil.rmtree(STATE_DIR)
        print(f"Reset: removed {removed} appended file(s) and the feed state. "
              "Frozen history untouched.")
        return

    wm = _load_watermark()
    if args.status:
        cmd_status(wm)
        return
    if not wm:
        wm = _bootstrap(wm)
    if args.redo:
        wm = cmd_redo(wm, args.redo)
        return

    _verify_history_untouched(wm)

    # The authoritative record of which days exist is the run log, not the
    # watermark. Deriving the work list by set difference makes the feed correct
    # under redos, gaps and out-of-order backfills: a day that has already been
    # written is never written twice, whatever the watermark says.
    history_end = pd.Timestamp(wm["history_end"])
    until = pd.Timestamp(args.until) if args.until else pd.Timestamp(date.today())
    candidate = pd.date_range(history_end + pd.Timedelta(days=1), until, freq="D")
    already = {r["date"] for r in wm["runs"]}
    days = pd.DatetimeIndex([d for d in candidate if d.date().isoformat() not in already])
    if len(days) == 0:
        print(f"Already current to {until.date()} — {len(already)} day(s) on record. "
              "Nothing to do.")
        return
    if len(days) > args.max_days:
        print(f"{len(days)} days behind; capping this run at {args.max_days}. "
              f"Run again to continue.")
        days = days[: args.max_days]

    print(f"Appending {len(days)} day(s): {days[0].date()} .. {days[-1].date()}")
    dims = factio.load_dims()
    fx = pd.read_parquet(RAW_DIR / "FactExchangeRate")

    t0 = time.time()
    for day in days:
        run = _append_day(dims, fx, day, wm)
        _verify_appended(day, run)
        wm["runs"].append(run)
        # Always the maximum date on record. Tracking it as "the last one I
        # just wrote" made it lie after a backfill filled an earlier gap.
        wm["last_appended_date"] = max(r["date"] for r in wm["runs"])
        _save_watermark(wm)   # after every day, so an interrupted run resumes cleanly
        print(f"  {run['date']}  {sum(run['rows'].values()):>7,} rows  "
              + " ".join(f"{k.replace('Fact','')}={v}" for k, v in run["rows"].items()))

    print(f"\nDone in {time.time() - t0:.1f}s. Watermark now {wm['last_appended_date']}.")


if __name__ == "__main__":
    main()
