"""Revision R1 — lengthen DimVoyage rotations to realistic loop sizes.

See 00_docs/ADR/ADR-001-voyage-rotation-length.md.

As first built, DimVoyage rotations carried 4-6 port calls. Real deep-sea loops
call at 10-16 ports in one direction: an Asia-North Europe string typically
covers several Chinese load ports, a South-East Asian hub, a Mediterranean or
Suez-adjacent call, then three or four North European discharge ports. The short
rotation had two consequences worth fixing rather than working around:

  1. FactPortCall could only reach ~31k rows against a contracted 96k, because
     calls are generated by exploding the rotation.
  2. Berth productivity, port dwell and transhipment analysis all had too few
     ports per voyage to show realistic variation.

This script rewrites RotationString and PortCallCount in place, preserving every
other column and every key. Run once, after build_dims.py, before build_facts.py.
"""

from __future__ import annotations

import numpy as np
import pandas as pd

from meridian.config import RAW_DIR, REFERENCE_DIR
from meridian.util import child_rng

# Target loop lengths. Mean ~14.1 calls x 6,800 voyages ~= 96,000 port calls,
# which is the contracted FactPortCall row count.
LOAD_PORT_RANGE = (4, 8)        # ports in the origin region
HUB_RANGE = (2, 4)              # transhipment hubs en route
DISCHARGE_PORT_RANGE = (4, 8)   # ports in the destination region

# Hubs that a deep-sea loop realistically transits, by the leg they sit on.
CORRIDOR_HUBS: dict[tuple[str, str], tuple[str, ...]] = {
    ("Asia", "Europe"): ("SGSIN", "MYPKG", "MYTPP", "EGPSD", "EGSUZ", "GRPIR", "ESVLC"),
    ("Europe", "Asia"): ("ESALG", "EGSUZ", "AEJEA", "INNSA", "SGSIN", "MYPKG"),
    ("Asia", "Americas"): ("KRPUS", "JPYOK", "TWKHH"),
    ("Americas", "Asia"): ("USOAK", "USSEA", "JPYOK"),
    ("Asia", "MEA"): ("SGSIN", "MYPKG", "INNSA", "OMSLL"),
    ("MEA", "Asia"): ("AEJEA", "INNSA", "MYPKG"),
    ("Europe", "Americas"): ("GBFXT", "ESALG"),
    ("Americas", "Europe"): ("USNYC", "USSAV"),
    ("Asia", "Oceania"): ("SGSIN", "IDJKT"),
    ("Oceania", "Asia"): ("AUSYD", "MYPKG"),
}
DEFAULT_HUBS = ("SGSIN", "MYPKG", "AEJEA", "EGPSD")

# Ports that must stay well represented so the congestion event of contract
# section 3.3 remains visible on roughly the same share of services as before.
CONGESTION_PORTS = ("NLRTM", "USLAX")
CONGESTION_PORT_SHARE = 0.44


def _region_ports(locations: pd.DataFrame) -> dict[str, list[str]]:
    seaports = locations[
        (locations["LocationKey"] > 0) & (locations["LocationType"] == "Seaport")
    ]
    return {
        region: grp["LocationCode"].tolist()
        for region, grp in seaports.groupby("TradeRegion")
    }


def main() -> None:
    rng = child_rng("ReviseVoyageRotations")

    voy_path = RAW_DIR / "DimVoyage" / "part-000.parquet"
    voyages = pd.read_parquet(voy_path)
    locations = pd.read_parquet(RAW_DIR / "DimLocation" / "part-000.parquet")
    services = pd.read_parquet(RAW_DIR / "DimService" / "part-000.parquet").set_index(
        "ServiceKey"
    )

    pool = _region_ports(locations)
    # DETERMINISM: this list is used as a fallback sampling pool, so its ORDER
    # feeds the RNG. A plain set() iterates in an order that depends on the
    # per-process PYTHONHASHSEED for string keys, which made the whole build
    # irreproducible across runs (see ADR-002). Sort it; keep a frozenset
    # alongside purely for O(1) membership tests.
    valid_codes_list = sorted(
        locations[locations["LocationKey"] > 0]["LocationCode"].tolist()
    )
    valid_codes = frozenset(valid_codes_list)

    real = voyages["VoyageKey"] > 0
    idx = voyages.index[real]
    n = len(idx)

    origin_region = (
        services["OriginRegion"].reindex(voyages.loc[idx, "ServiceKey"]).to_numpy()
    )
    dest_region = (
        services["DestinationRegion"].reindex(voyages.loc[idx, "ServiceKey"]).to_numpy()
    )
    is_backhaul = voyages.loc[idx, "Direction"].to_numpy() == "Backhaul"

    # On a backhaul the loop runs the other way round.
    o_reg = np.where(is_backhaul, dest_region, origin_region)
    d_reg = np.where(is_backhaul, origin_region, dest_region)

    n_load = rng.integers(LOAD_PORT_RANGE[0], LOAD_PORT_RANGE[1] + 1, size=n)
    n_hub = rng.integers(HUB_RANGE[0], HUB_RANGE[1] + 1, size=n)
    n_disc = rng.integers(DISCHARGE_PORT_RANGE[0], DISCHARGE_PORT_RANGE[1] + 1, size=n)
    force_congested = rng.random(n) < CONGESTION_PORT_SHARE

    rotations: list[str] = []
    for i in range(n):  # 6,800 voyages — a dimension loop, not a fact loop
        load_pool = pool.get(o_reg[i]) or valid_codes_list
        disc_pool = pool.get(d_reg[i]) or valid_codes_list
        hubs = CORRIDOR_HUBS.get((o_reg[i], d_reg[i]), DEFAULT_HUBS)
        hubs = [h for h in hubs if h in valid_codes] or list(DEFAULT_HUBS)

        loads = rng.choice(
            load_pool, size=min(n_load[i], len(load_pool)), replace=False
        ).tolist()
        mids = rng.choice(
            hubs, size=min(n_hub[i], len(hubs)), replace=False
        ).tolist()
        discs = rng.choice(
            disc_pool, size=min(n_disc[i], len(disc_pool)), replace=False
        ).tolist()

        if force_congested[i]:
            pick = CONGESTION_PORTS[int(rng.integers(0, len(CONGESTION_PORTS)))]
            if pick in valid_codes and pick not in discs:
                discs[-1] = pick

        seq = loads + mids + discs
        # Collapse any accidental immediate repeat; a vessel does not call twice
        # in a row at the same berth.
        deduped = [seq[0]]
        for code in seq[1:]:
            if code != deduped[-1]:
                deduped.append(code)
        rotations.append("-".join(deduped))

    voyages.loc[idx, "RotationString"] = rotations
    # Widen before assigning: the column is int8 and the new counts are int64,
    # which pandas refuses to downcast silently. Cast back once populated.
    voyages["PortCallCount"] = voyages["PortCallCount"].astype(np.int16)
    voyages.loc[idx, "PortCallCount"] = np.array(
        [len(r.split("-")) for r in rotations], dtype=np.int16
    )
    voyages["PortCallCount"] = voyages["PortCallCount"].astype(np.int8)

    voyages.to_parquet(voy_path, compression="snappy", index=False)
    REFERENCE_DIR.mkdir(parents=True, exist_ok=True)
    voyages.to_csv(REFERENCE_DIR / "DimVoyage.csv", index=False)

    counts = voyages.loc[idx, "PortCallCount"]
    touching = (
        voyages.loc[idx, "RotationString"]
        .str.contains("|".join(CONGESTION_PORTS))
        .mean()
    )
    print(f"Revised {n} voyage rotations")
    print(f"  port calls per voyage: mean {counts.mean():.2f}  min {counts.min()}  max {counts.max()}")
    print(f"  implied FactPortCall rows: {int(counts.sum()):,}")
    print(f"  rotations touching a congestion port: {touching:.1%}")


if __name__ == "__main__":
    main()
