"use strict";
/* Topic 1 - Aggregations. Add challenges to the `challenges` array (see AUTHORING.md). */
registerTopic({
  id:'T01',title:'Aggregations',order:1,
  concept:[
    'A measure is a formula that Power BI evaluates again for every cell of a visual, using the filters that apply to that cell. The simplest measures aggregate one column into one number: `SUM`, `AVERAGE`, `MIN`, `MAX`. `COUNT` counts the non-blank values of a column, `COUNTROWS` counts the rows of a table, and `DISTINCTCOUNT` counts different values. Columns are always written `Table[Column]`.',
    '',
    '  Total Revenue = SUM(Shipment[Revenue])',
    '  Shipments = COUNTROWS(Shipment)',
    '  Customers = DISTINCTCOUNT(Shipment[CustomerKey])',
    '',
    'An aggregation over no rows is BLANK, not 0. The functions respect whatever filters the visual applies, so the same formula gives a different answer in each row.'
  ].join('\n'),
  challenges:[
    {id:'T01-01',v1:'b1',level:'Beginner',title:'Total Revenue',by:['Shipment[Mode]'],checks:['slash','unqual','sumxRedundant'],
     prompt:'Write a measure that returns total revenue: the sum of the Revenue column of Shipment.',
     hint:'SUM adds up one column. Columns are written Table[Column], so here it is Shipment[Revenue].',
     ref:'SUM(Shipment[Revenue])',
     alts:[{code:'SUMX(Shipment, Shipment[Revenue])',warn:'sumxRedundant'}],
     wrongs:[{code:'SUM(Shipment[Cost])'},{code:'COUNTROWS(Shipment)'}],
     why:'SUM(Shipment[Revenue]) respects whatever filters are active (e.g. each Mode row in a visual) and adds up the column.',
     oracle:(D,c)=>H.sumOrNull(H.vis(D,c),s=>s.Revenue)},
    {id:'T01-02',v1:'b2',level:'Beginner',title:'Shipment Count',by:['Shipment[Mode]'],checks:['slash','unqual'],
     prompt:'Write a measure that counts the shipments (one row of Shipment = one shipment).',
     hint:'COUNTROWS counts the rows of a table. Give it the table itself, with no column.',
     ref:'COUNTROWS(Shipment)',
     alts:[{code:'COUNT(Shipment[ShipmentID])'},{code:'DISTINCTCOUNT(Shipment[ShipmentID])'}],
     wrongs:[{code:'DISTINCTCOUNT(Shipment[CustomerKey])'},{code:'SUM(Shipment[IsOnTime])'}],
     why:'COUNTROWS(Shipment) counts the shipment rows left visible by the current filters.',
     oracle:(D,c)=>H.vis(D,c).length},
    {id:'T01-03',v1:'b3',level:'Beginner',title:'Average Cost',by:['Shipment[Mode]'],checks:['slash','unqual'],
     prompt:'Write a measure for the average Cost per shipment.',
     hint:'AVERAGE takes a column and averages its values.',
     ref:'AVERAGE(Shipment[Cost])',
     alts:[{code:'DIVIDE(SUM(Shipment[Cost]), COUNTROWS(Shipment))'},{code:'AVERAGEX(Shipment, Shipment[Cost])'}],
     wrongs:[{code:'SUM(Shipment[Cost])'},{code:'AVERAGE(Shipment[Revenue])'}],
     why:'AVERAGE(Shipment[Cost]) is the sum of Cost divided by the number of shipments, in the current filter context.',
     oracle:(D,c)=>{const r=H.vis(D,c);return r.length?H.sum(r,s=>s.Cost)/r.length:null;}},
    {id:'T01-04',v1:'b4',level:'Beginner',title:'Distinct Customers',by:['Shipment[Mode]'],checks:['slash','unqual'],
     prompt:'How many different customers have shipped? Count each customer once, no matter how many shipments they have.',
     hint:'DISTINCTCOUNT counts unique values in a column. Which column identifies the customer on each shipment?',
     ref:'DISTINCTCOUNT(Shipment[CustomerKey])',
     alts:[{code:'COUNTROWS(VALUES(Shipment[CustomerKey]))'}],
     wrongs:[{code:'COUNTROWS(Shipment)'},{code:'DISTINCTCOUNT(Customer[CustomerKey])'}],
     why:'Use the key on the fact table. DISTINCTCOUNT(Customer[CustomerKey]) counts every customer in the dimension, even ones with no visible shipments, because filters on Shipment do not flow to Customer.',
     oracle:(D,c)=>new Set(H.vis(D,c).map(s=>s.CustomerKey)).size},
    {id:'T01-05',level:'Beginner',title:'Heaviest Shipment',by:['Shipment[Mode]'],checks:['slash','unqual'],
     prompt:'What is the weight, in kg, of the single heaviest shipment? Show it per Mode.',
     hint:'MAX returns the largest value of a column. Weight is a column of Shipment.',
     ref:'MAX(Shipment[Weight])',
     alts:[{code:'MAXX(Shipment, Shipment[Weight])'}],
     wrongs:[{code:'MIN(Shipment[Weight])'},{code:'SUM(Shipment[Weight])'},{code:'AVERAGE(Shipment[Weight])'}],
     why:'MAX looks at the shipments left visible by the current filters and returns the largest Weight. SUM would add the weights of all of them, and MIN would give the lightest.',
     oracle:(D,c)=>{const r=H.vis(D,c);return r.length?Math.max.apply(null,r.map(s=>s.Weight)):null;}},
    {id:'T01-06',level:'Intermediate',title:'Weight Range',by:['Shipment[Mode]'],checks:['slash','unqual'],
     prompt:'The operations team wants the spread of shipment sizes: the weight of the heaviest shipment minus the weight of the lightest shipment, in kg.',
     hint:'You can subtract two aggregations: MAX(...) - MIN(...).',
     ref:'MAX(Shipment[Weight]) - MIN(Shipment[Weight])',
     alts:[{code:'MAXX(Shipment, Shipment[Weight]) - MINX(Shipment, Shipment[Weight])'}],
     wrongs:[{code:'MAX(Shipment[Weight])'},{code:'MAX(Shipment[Weight]) - AVERAGE(Shipment[Weight])'}],
     why:'Both MAX and MIN respect the filters of the current row, so every Mode gets its own heaviest and lightest shipment.',
     oracle:(D,c)=>{const r=H.vis(D,c);if(!r.length)return null;const w=r.map(s=>s.Weight);return Math.max.apply(null,w)-Math.min.apply(null,w);}},
    {id:'T01-07',level:'Intermediate',title:'Missing Revenue Check',by:['Shipment[Mode]'],checks:['slash','unqual'],
     prompt:'Data-quality check: how many shipments have no Revenue recorded (the cell is empty/blank)? A revenue of 0 is a value, not a blank. A healthy data set shows 0 in every row.',
     hint:'COUNTBLANK(column) counts the empty cells of a column. Alternatively, compare COUNTROWS (all rows) with COUNT (rows that have a value).',
     ref:'COUNTBLANK(Shipment[Revenue])',
     alts:[{code:'COUNTROWS(Shipment) - COUNT(Shipment[Revenue])'},{code:'COUNTROWS(FILTER(Shipment, ISBLANK(Shipment[Revenue])))'}],
     wrongs:[{code:'COUNTROWS(Shipment)'},{code:'CALCULATE(COUNTROWS(Shipment), Shipment[Ffe] = 0)'},{code:'COUNT(Shipment[Revenue])'}],
     why:'COUNT counts the cells that have a value and COUNTROWS counts every row, so their difference is the number of blanks, which is what COUNTBLANK returns. A zero (like Ffe = 0 on Air shipments) is not blank.',
     oracle:(D,c)=>H.vis(D,c).filter(s=>s.Revenue==null).length},
    {id:'T01-08',level:'Pro',title:'Revenue per Active Shipping Day',by:['Shipment[Mode]'],checks:['slash','unqual'],
     prompt:'Average revenue per active shipping day: total revenue divided by the number of different dates (Shipment[DateKey]) on which at least one shipment was booked. Two shipments booked on the same day count as one day.',
     hint:'The denominator is a distinct count of the date column, not a count of shipments. Wrap the division in DIVIDE.',
     ref:'DIVIDE(SUM(Shipment[Revenue]), DISTINCTCOUNT(Shipment[DateKey]))',
     alts:[{code:'DIVIDE(SUM(Shipment[Revenue]), COUNTROWS(VALUES(Shipment[DateKey])))'},{code:'DIVIDE([Total Revenue], DISTINCTCOUNT(Shipment[DateKey]))'}],
     wrongs:[{code:'DIVIDE(SUM(Shipment[Revenue]), COUNTROWS(Shipment))'},{code:'DIVIDE(SUM(Shipment[Revenue]), DISTINCTCOUNT(Shipment[CustomerKey]))'},{code:'DIVIDE(SUM(Shipment[Revenue]), COUNTROWS(Date))'}],
     why:'DISTINCTCOUNT counts each booking date once, so a day with three shipments is one day. Dividing by COUNTROWS gives revenue per shipment instead, and COUNTROWS(Date) counts every calendar day, even days with no shipments.',
     oracle:(D,c)=>{const r=H.vis(D,c);return H.div(H.sumOrNull(r,s=>s.Revenue),new Set(r.map(s=>s.DateKey)).size);}}
  ]
});
