"use strict";
/* Topic 2 - Measures & DIVIDE. Library measures ([Total Revenue], [Profit] ...) may be referenced from here on. */
registerTopic({
  id:'T02',title:'Measures & DIVIDE',order:2,
  concept:[
    'A measure can be built from other measures. The page has a small library you can reference by name: `[Total Revenue]`, `[Total Cost]`, `[Profit]`, `[Shipments]`, `[Total FFE]`, `[On-Time %]` (see "Measures you can use"). A ratio must be built from totals, and it must not divide with `/` when the denominator can be zero: `DIVIDE(numerator, denominator, [alternate])` returns BLANK (or the alternate result) instead of an error.',
    '',
    '  Profit = [Total Revenue] - [Total Cost]',
    '  Margin % = DIVIDE([Profit], [Total Revenue])',
    '',
    'BLANK is not 0: a visual hides rows where a measure is BLANK, but shows rows where it is 0.'
  ].join('\n'),
  challenges:[
    {id:'T02-01',v1:'b5',level:'Beginner',title:'Total Profit',by:['Shipment[Mode]'],checks:['slash','sumxRedundant'],
     prompt:'Write a measure for total profit: total Revenue minus total Cost.',
     hint:'You can subtract two aggregations: SUM(...) - SUM(...). A row-by-row SUMX also works, and so do the library measures.',
     ref:'SUM(Shipment[Revenue]) - SUM(Shipment[Cost])',
     alts:[{code:'SUMX(Shipment, Shipment[Revenue] - Shipment[Cost])'},{code:'[Total Revenue] - [Total Cost]'},{code:'[Profit]'}],
     wrongs:[{code:'SUM(Shipment[Revenue])'},{code:'AVERAGE(Shipment[Revenue]) - AVERAGE(Shipment[Cost])'}],
     why:'All forms give the same answer: the sum of per-row profits equals total revenue minus total cost.',
     oracle:(D,c)=>{const r=H.vis(D,c);return H.sumOrNull(r,s=>s.Revenue-s.Cost);}},
    {id:'T02-02',level:'Beginner',title:'Revenue per Shipment',by:['Shipment[Mode]'],checks:['slash','unqual'],
     prompt:'On average, how much revenue does one shipment bring in? Build it from the library measures [Total Revenue] and [Shipments].',
     hint:'Divide one library measure by the other with DIVIDE(numerator, denominator). Revenue goes on top.',
     ref:'DIVIDE([Total Revenue], [Shipments])',
     alts:[{code:'DIVIDE(SUM(Shipment[Revenue]), COUNTROWS(Shipment))'},{code:'AVERAGE(Shipment[Revenue])'}],
     wrongs:[{code:'DIVIDE([Shipments], [Total Revenue])'},{code:'DIVIDE([Total Revenue], [Total FFE])'},{code:'[Total Revenue]'}],
     why:'Revenue divided by the number of shipments is the average revenue per shipment. Dividing by [Total FFE] counts containers instead, and Air shipments have no FFE at all.',
     oracle:(D,c)=>{const r=H.vis(D,c);return H.div(H.sum(r,s=>s.Revenue),r.length);}},
    {id:'T02-03',level:'Beginner',title:'Cost % of Revenue',by:['Shipment[Mode]'],checks:['slash','unqual','avgRatio'],
     prompt:'What share of revenue is eaten by cost? Return Cost divided by Revenue, and make the measure return 0 (not an error) when there is no revenue.',
     hint:'DIVIDE has an optional third argument, the alternate result: DIVIDE(numerator, denominator, 0).',
     ref:'DIVIDE([Total Cost], [Total Revenue], 0)',
     alts:[{code:'DIVIDE(SUM(Shipment[Cost]), SUM(Shipment[Revenue]), 0)'},{code:'DIVIDE([Total Cost], [Total Revenue])'},{code:'1 - DIVIDE([Profit], [Total Revenue])'}],
     wrongs:[{code:'DIVIDE([Total Revenue], [Total Cost], 0)'},{code:'AVERAGEX(Shipment, DIVIDE(Shipment[Cost], Shipment[Revenue]))',warn:'avgRatio'},{code:'[Total Cost]'}],
     why:'Cost % is the ratio of two totals. The third argument of DIVIDE is only used when the denominator is 0 or BLANK; with data present every form agrees. Averaging per-shipment ratios (AVERAGEX) gives a small shipment the same vote as a large one.',
     oracle:(D,c)=>{const r=H.vis(D,c);return H.div(H.sum(r,s=>s.Cost),H.sum(r,s=>s.Revenue));}},
    {id:'T02-04',level:'Intermediate',title:'Late Shipments',by:['Shipment[Mode]'],checks:['slash','unqual'],
     prompt:'How many shipments were late? IsOnTime is 1 for on-time and 0 for late. Use the library measure [Shipments] if you like.',
     hint:'Late = all shipments minus on-time shipments. SUM(Shipment[IsOnTime]) counts the on-time ones.',
     ref:'[Shipments] - SUM(Shipment[IsOnTime])',
     alts:[{code:'COUNTROWS(Shipment) - SUM(Shipment[IsOnTime])'},{code:'CALCULATE(COUNTROWS(Shipment), Shipment[IsOnTime] = 0)'}],
     wrongs:[{code:'SUM(Shipment[IsOnTime])'},{code:'[Shipments]'}],
     why:'Because IsOnTime is a 0/1 flag, its sum is the on-time count, and the late count is whatever is left of the total.',
     oracle:(D,c)=>{const r=H.vis(D,c);return r.length?r.length-H.sum(r,s=>s.IsOnTime):null;}},
    {id:'T02-05',v1:'i2',level:'Intermediate',title:'Margin %',by:['Shipment[Mode]'],checks:['slash','avgRatio'],
     prompt:'Margin % = (Revenue - Cost) / Revenue, computed on totals. Return BLANK rather than an error when revenue is zero.',
     hint:'Use DIVIDE(numerator, denominator). Both parts are sums, not averages of per-shipment percentages.',
     ref:'DIVIDE(SUM(Shipment[Revenue]) - SUM(Shipment[Cost]), SUM(Shipment[Revenue]))',
     alts:[{code:'DIVIDE(SUMX(Shipment, Shipment[Revenue] - Shipment[Cost]), SUM(Shipment[Revenue]))'},
           {code:'DIVIDE([Profit], [Total Revenue])'},
           {code:'(SUM(Shipment[Revenue]) - SUM(Shipment[Cost])) / SUM(Shipment[Revenue])',warn:'slash'}],
     wrongs:[{code:'AVERAGEX(Shipment, DIVIDE(Shipment[Revenue] - Shipment[Cost], Shipment[Revenue]))',warn:'avgRatio'},
             {code:'SUM(Shipment[Revenue]) - SUM(Shipment[Cost])'}],
     why:'A ratio must be built from totals (ratio of sums). Averaging per-shipment percentages gives small shipments the same weight as large ones.',
     oracle:(D,c)=>{const r=H.vis(D,c);const rev=H.sum(r,s=>s.Revenue);return H.div(rev-H.sum(r,s=>s.Cost),rev);}},
    {id:'T02-06',v1:'i3',level:'Intermediate',title:'On-Time %',by:['Shipment[Mode]'],checks:['slash'],
     prompt:'Share of shipments that were on time, written from scratch (do not just reference [On-Time %]). IsOnTime is 1 when on time and 0 otherwise.',
     hint:'IsOnTime is 0/1, so its average is already the on-time rate. DIVIDE(on-time count, all shipments) works as well.',
     ref:'DIVIDE(SUM(Shipment[IsOnTime]), COUNTROWS(Shipment))',
     alts:[{code:'AVERAGE(Shipment[IsOnTime])'},{code:'DIVIDE(CALCULATE(COUNTROWS(Shipment), Shipment[IsOnTime] = 1), COUNTROWS(Shipment))'}],
     wrongs:[{code:'SUM(Shipment[IsOnTime])'},{code:'DIVIDE(COUNTROWS(Shipment), SUM(Shipment[IsOnTime]))'}],
     why:'A 0/1 flag averages into a rate: AVERAGE(IsOnTime) = SUM(IsOnTime) / COUNTROWS.',
     oracle:(D,c)=>{const r=H.vis(D,c);return H.div(H.sum(r,s=>s.IsOnTime),r.length);}},
    {id:'T02-07',level:'Intermediate',title:'Late %',by:['Shipment[Mode]'],checks:['slash','unqual'],
     prompt:'What percentage of shipments were late? Build it on top of the library measures, for example [On-Time %] or [Shipments].',
     hint:'Late % and on-time % add up to 100%, so one is 1 minus the other. Or divide the late count by all shipments.',
     ref:'1 - [On-Time %]',
     alts:[{code:'DIVIDE([Shipments] - SUM(Shipment[IsOnTime]), [Shipments])'},{code:'1 - AVERAGE(Shipment[IsOnTime])'},{code:'DIVIDE(CALCULATE(COUNTROWS(Shipment), Shipment[IsOnTime] = 0), COUNTROWS(Shipment))'}],
     wrongs:[{code:'[On-Time %]'},{code:'DIVIDE([Shipments] - SUM(Shipment[IsOnTime]), SUM(Shipment[IsOnTime]))'},{code:'[Shipments] - SUM(Shipment[IsOnTime])'}],
     why:'A measure can reuse another measure. 1 - [On-Time %] reuses a ratio of totals. Dividing late shipments by on-time shipments gives a different ratio (late per on-time shipment), not a percentage of all shipments.',
     oracle:(D,c)=>{const r=H.vis(D,c);return r.length?1-H.sum(r,s=>s.IsOnTime)/r.length:null;}},
    {id:'T02-08',level:'Pro',title:'Profit per Tonne',by:['Shipment[Mode]'],checks:['slash','unqual','avgRatio'],
     prompt:'Profit per tonne moved: total profit divided by total weight in tonnes. Weight is stored in kg, and 1 tonne = 1,000 kg. Use the library measure [Profit].',
     hint:'DIVIDE([Profit], total kg) gives profit per kg. Convert to tonnes by multiplying by 1,000 (or dividing the kg by 1,000 first).',
     ref:'DIVIDE([Profit], SUM(Shipment[Weight])) * 1000',
     alts:[{code:'DIVIDE([Profit], SUM(Shipment[Weight]) / 1000)',warn:'slash'},{code:'DIVIDE(SUM(Shipment[Revenue]) - SUM(Shipment[Cost]), SUM(Shipment[Weight])) * 1000'}],
     wrongs:[{code:'DIVIDE([Profit], SUM(Shipment[Weight]))'},{code:'AVERAGEX(Shipment, DIVIDE(Shipment[Revenue] - Shipment[Cost], Shipment[Weight])) * 1000',warn:'avgRatio'},{code:'DIVIDE([Profit], [Shipments])'}],
     why:'Both the profit and the weight are totals, so divide the totals and fix the unit last. Forgetting the unit gives profit per kg, which is 1,000 times too small. Averaging per-shipment profit-per-kg values lets a tiny shipment count as much as a full container.',
     oracle:(D,c)=>{const r=H.vis(D,c);return H.div(H.sum(r,s=>s.Revenue-s.Cost),H.sum(r,s=>s.Weight))==null?null:H.sum(r,s=>s.Revenue-s.Cost)/H.sum(r,s=>s.Weight)*1000;}}
  ]
});
