"use strict";
/* Topic 3 - Iterators. */
registerTopic({
  id:'T03',title:'Iterators',order:3,
  concept:[
    'An iterator (`SUMX`, `AVERAGEX`, `MAXX`, `MINX`, `COUNTX`) walks a table row by row, evaluates an expression in each row, and then aggregates the results. Inside the expression you can use the columns of the current row, and `RELATED(Customer[Segment])` fetches a column from the one-side of a relationship.',
    '',
    '  Gross Weight Revenue = SUMX(Shipment, Shipment[Revenue] * Shipment[Weight])',
    '  Key Revenue = SUMX(Shipment, IF(RELATED(Customer[Segment]) = "Key", Shipment[Revenue], 0))',
    '',
    'Use an iterator when the value needs more than one column per row. A weighted average is SUMX(...) divided by the total weight; an average of per-row ratios (AVERAGEX of a division) is usually not what you want.'
  ].join('\n'),
  challenges:[
    {id:'T03-01',level:'Beginner',title:'Profit, Row by Row',by:['Shipment[Mode]'],checks:['unqual'],
     prompt:'Total profit, calculated one shipment at a time: for each shipment take Revenue minus Cost, then add the results up.',
     hint:'SUMX(table, expression) evaluates the expression on every row of the table and adds the results. Here the table is Shipment.',
     ref:'SUMX(Shipment, Shipment[Revenue] - Shipment[Cost])',
     alts:[{code:'SUM(Shipment[Revenue]) - SUM(Shipment[Cost])'}],
     wrongs:[{code:'SUMX(Shipment, Shipment[Revenue])'},{code:'SUMX(Shipment, Shipment[Cost] - Shipment[Revenue])'}],
     why:'SUMX evaluates the expression in each row and then sums. For a simple difference the result equals SUM - SUM, but the iterator form keeps working when the per-row logic gets more complicated.',
     oracle:(D,c)=>H.sumOrNull(H.vis(D,c),s=>s.Revenue-s.Cost)},
    {id:'T03-02',level:'Beginner',title:'Late-Shipment Revenue',by:['Shipment[Mode]'],checks:['unqual'],
     prompt:'How much revenue comes from shipments that were late? IsOnTime is 1 for on-time and 0 for late. Add up the Revenue of the late shipments only.',
     hint:'Iterate over Shipment and keep Revenue only when IsOnTime is 0, for example with IF, or iterate over FILTER(Shipment, ...).',
     ref:'SUMX(Shipment, IF(Shipment[IsOnTime] = 0, Shipment[Revenue], 0))',
     alts:[{code:'SUMX(FILTER(Shipment, Shipment[IsOnTime] = 0), Shipment[Revenue])'},{code:'SUMX(Shipment, Shipment[Revenue] * (1 - Shipment[IsOnTime]))'},{code:'CALCULATE(SUM(Shipment[Revenue]), Shipment[IsOnTime] = 0)'}],
     wrongs:[{code:'SUM(Shipment[Revenue])'},{code:'SUMX(Shipment, Shipment[Revenue] * Shipment[IsOnTime])'}],
     why:'Each row contributes its Revenue only when the shipment is late; on-time rows contribute 0. Multiplying by IsOnTime instead keeps the on-time revenue, which is the opposite.',
     oracle:(D,c)=>H.sumOrNull(H.vis(D,c).filter(s=>s.IsOnTime===0),s=>s.Revenue)},
    {id:'T03-03',level:'Beginner',title:'Average Profit per Shipment',by:['Shipment[Mode]'],checks:['slash','unqual'],
     prompt:'The average profit of one shipment, where a shipment\'s profit is its Revenue minus its Cost.',
     hint:'AVERAGEX(table, expression) evaluates the expression for every row and averages the results.',
     ref:'AVERAGEX(Shipment, Shipment[Revenue] - Shipment[Cost])',
     alts:[{code:'DIVIDE(SUM(Shipment[Revenue]) - SUM(Shipment[Cost]), COUNTROWS(Shipment))'},{code:'AVERAGE(Shipment[Revenue]) - AVERAGE(Shipment[Cost])'}],
     wrongs:[{code:'SUM(Shipment[Revenue]) - SUM(Shipment[Cost])'},{code:'AVERAGE(Shipment[Revenue])'}],
     why:'AVERAGEX builds a list of per-shipment profits and averages it. The total profit would be the SUM of that list, and AVERAGE(Revenue) ignores cost altogether.',
     oracle:(D,c)=>{const r=H.vis(D,c);return r.length?H.sum(r,s=>s.Revenue-s.Cost)/r.length:null;}},
    {id:'T03-04',level:'Intermediate',title:'Best Single-Shipment Profit',by:['Shipment[Mode]'],checks:['unqual'],
     prompt:'What is the highest profit (Revenue minus Cost) earned by any single shipment?',
     hint:'MAXX(table, expression) evaluates the expression on every row and returns the largest result. MAX(Revenue) - MAX(Cost) would mix two different shipments.',
     ref:'MAXX(Shipment, Shipment[Revenue] - Shipment[Cost])',
     alts:[],
     wrongs:[{code:'MAX(Shipment[Revenue]) - MAX(Shipment[Cost])'},{code:'MAX(Shipment[Revenue]) - MIN(Shipment[Cost])'},{code:'MINX(Shipment, Shipment[Revenue] - Shipment[Cost])'}],
     why:'The profit has to be worked out for each shipment first, and only then can the largest be picked. MAX(Revenue) - MAX(Cost) subtracts the cost of one shipment from the revenue of another.',
     oracle:(D,c)=>{const r=H.vis(D,c);return r.length?Math.max.apply(null,r.map(s=>s.Revenue-s.Cost)):null;}},
    {id:'T03-05',level:'Intermediate',title:'Revenue from German Customers',by:['Shipment[Mode]'],checks:['unqual'],
     prompt:'Total revenue of shipments whose customer is based in Germany. Country is a column of Customer, and each Shipment row belongs to one customer.',
     hint:'Inside a row-by-row iterator over Shipment, RELATED(Customer[Country]) looks up the country of that shipment\'s customer.',
     ref:'SUMX(Shipment, IF(RELATED(Customer[Country]) = "Germany", Shipment[Revenue], 0))',
     alts:[{code:'SUMX(FILTER(Shipment, RELATED(Customer[Country]) = "Germany"), Shipment[Revenue])'},{code:'CALCULATE(SUM(Shipment[Revenue]), Customer[Country] = "Germany")'}],
     wrongs:[{code:'SUM(Shipment[Revenue])'},{code:'SUMX(Shipment, IF(RELATED(Customer[Country]) = "USA", Shipment[Revenue], 0))'}],
     why:'RELATED follows the many-to-one relationship from the current Shipment row to its Customer row, so the iterator can test a Customer column row by row.',
     oracle:(D,c)=>H.sumOrNull(H.vis(D,c).filter(s=>s._c.Country==='Germany'),s=>s.Revenue)},
    {id:'T03-06',level:'Intermediate',title:'On-Time % by Weight',by:['Shipment[Mode]'],checks:['unqual'],
     prompt:'Of all the kilograms we moved, what share travelled on shipments that were on time? That is a weight-weighted on-time rate: heavy shipments count more than light ones.',
     hint:'Numerator: add up Weight only for on-time shipments (Weight times IsOnTime in each row). Denominator: total Weight. Use DIVIDE.',
     ref:'DIVIDE(SUMX(Shipment, Shipment[Weight] * Shipment[IsOnTime]), SUM(Shipment[Weight]))',
     alts:[{code:'DIVIDE(SUMX(FILTER(Shipment, Shipment[IsOnTime] = 1), Shipment[Weight]), SUM(Shipment[Weight]))'},{code:'DIVIDE(CALCULATE(SUM(Shipment[Weight]), Shipment[IsOnTime] = 1), SUM(Shipment[Weight]))'}],
     wrongs:[{code:'AVERAGE(Shipment[IsOnTime])'},{code:'SUMX(Shipment, Shipment[Weight] * Shipment[IsOnTime])'},{code:'DIVIDE(SUM(Shipment[IsOnTime]), SUM(Shipment[Weight]))'}],
     why:'A weighted average is the sum of (value x weight) divided by the sum of the weights. AVERAGE(IsOnTime) gives every shipment one vote, however heavy it is.',
     oracle:(D,c)=>{const r=H.vis(D,c);return H.div(H.sum(r,s=>s.Weight*s.IsOnTime),H.sum(r,s=>s.Weight));}},
    {id:'T03-07',level:'Intermediate',title:'True Revenue per kg',by:['Shipment[Mode]'],checks:['slash','unqual','avgRatio'],
     prompt:'Revenue per kg shipped, as one rate for the whole group: total revenue divided by total kilograms. (Not the average of each shipment\'s own revenue-per-kg.)',
     hint:'Divide the two totals. Averaging per-shipment ratios treats a 100 kg parcel like a 20-tonne container.',
     ref:'DIVIDE(SUM(Shipment[Revenue]), SUM(Shipment[Weight]))',
     alts:[{code:'DIVIDE([Total Revenue], SUM(Shipment[Weight]))'},{code:'DIVIDE(SUMX(Shipment, Shipment[Revenue]), SUMX(Shipment, Shipment[Weight]))'}],
     wrongs:[{code:'AVERAGEX(Shipment, DIVIDE(Shipment[Revenue], Shipment[Weight]))',warn:'avgRatio'},{code:'DIVIDE(AVERAGE(Shipment[Revenue]), COUNTROWS(Shipment))'},{code:'DIVIDE(SUM(Shipment[Weight]), SUM(Shipment[Revenue]))'}],
     why:'This is the average-of-ratios trap. The per-shipment average gives light air parcels, which earn a lot per kg, the same weight as heavy ocean loads. The ratio of totals weights each shipment by its kilograms.',
     oracle:(D,c)=>{const r=H.vis(D,c);return H.div(H.sum(r,s=>s.Revenue),H.sum(r,s=>s.Weight));}},
    {id:'T03-08',level:'Pro',title:'Average Revenue per Active Customer',by:['Shipment[Mode]'],checks:['slash','unqual'],
     prompt:'For each customer that has shipments in the current selection, add up that customer\'s revenue; then average those customer totals. Customers with no shipments in the selection are not counted.',
     hint:'Iterate over the distinct customers on the shipment table: AVERAGEX(VALUES(Shipment[CustomerKey]), ...). Inside, a measure or CALCULATE turns the current customer into a filter.',
     ref:'AVERAGEX(VALUES(Shipment[CustomerKey]), CALCULATE(SUM(Shipment[Revenue])))',
     alts:[{code:'AVERAGEX(VALUES(Shipment[CustomerKey]), [Total Revenue])'},{code:'DIVIDE(SUM(Shipment[Revenue]), DISTINCTCOUNT(Shipment[CustomerKey]))'},{code:'AVERAGEX(Customer, CALCULATE(SUM(Shipment[Revenue])))'}],
     wrongs:[{code:'AVERAGE(Shipment[Revenue])'},{code:'DIVIDE(SUM(Shipment[Revenue]), COUNTROWS(Customer))'},{code:'AVERAGEX(Shipment, CALCULATE(SUM(Shipment[Revenue])))'}],
     why:'Inside the iterator, CALCULATE (or a measure) turns the current customer into a filter, so each step returns that customer\'s total. AVERAGE(Revenue) averages shipments instead, and dividing by COUNTROWS(Customer) also counts customers who did not ship in this Mode.',
     oracle:(D,c)=>{const t=H.byCustomer(H.vis(D,c),s=>s.Revenue);return t.length?H.sum(t,x=>x.val)/t.length:null;}},
    {id:'T03-09',level:'Pro',title:'Average of Customer Margins',by:['Shipment[Mode]'],checks:['slash','unqual','avgRatio'],refWarns:['avgRatio'],
     prompt:'Give every customer one vote: work out each customer\'s own margin % (their profit divided by their revenue), then take the simple average of those percentages across the customers that have shipments in the selection.',
     hint:'Iterate over Customer and compute DIVIDE([Profit], [Total Revenue]) for each customer (the measures see the current customer as a filter). Customers without shipments return BLANK and are skipped.',
     ref:'AVERAGEX(Customer, DIVIDE([Profit], [Total Revenue]))',
     alts:[{code:'AVERAGEX(VALUES(Shipment[CustomerKey]), DIVIDE([Profit], [Total Revenue]))'}],
     wrongs:[{code:'DIVIDE([Profit], [Total Revenue])'},{code:'AVERAGEX(Shipment, DIVIDE(Shipment[Revenue] - Shipment[Cost], Shipment[Revenue]))',warn:'avgRatio'}],
     why:'Here the average of ratios is intended, one per customer. Compare it with the ratio of totals, which weights big customers more, and with a per-shipment average, which weights frequent shippers more. The three give different answers.',
     oracle:(D,c)=>{const r=H.vis(D,c);const by={};r.forEach(s=>{const o=by[s.CustomerKey]||(by[s.CustomerKey]={rev:0,cost:0});o.rev+=s.Revenue;o.cost+=s.Cost;});const v=Object.keys(by).map(k=>(by[k].rev-by[k].cost)/by[k].rev);return v.length?H.sum(v,x=>x)/v.length:null;}}
  ]
});
