"use strict";
/* Topic 4 - CALCULATE basics. */
registerTopic({
  id:'T04',title:'CALCULATE basics',order:4,
  concept:[
    '`CALCULATE(expression, filter1, filter2, ...)` evaluates the expression in a modified filter context. A True/False filter on one column, such as `Shipment[Mode] = "Ocean"`, replaces any existing filter on that column and keeps all the others. Several filters are combined with AND. For OR use `IN {...}` or `||` on the same column. A filter on Customer or Date flows down the relationship to Shipment.',
    '',
    '  Ocean Revenue = CALCULATE([Total Revenue], Shipment[Mode] = "Ocean")',
    '  Key Revenue = CALCULATE([Total Revenue], Customer[Segment] = "Key")',
    '  Air or Road = CALCULATE([Total Revenue], Shipment[Mode] IN {"Air", "Road"})',
    '',
    '`KEEPFILTERS(filter)` intersects with the existing filter on that column instead of replacing it.'
  ].join('\n'),
  challenges:[
    {id:'T04-01',v1:'i1',level:'Intermediate',title:'Ocean Revenue',by:['Shipment[Region]'],checks:['slash','unqual','filterInCalc'],
     prompt:'Total revenue of Ocean shipments only. It will be shown by Region, so the Region filter must still apply.',
     hint:'CALCULATE(expression, filter). A True/False filter on one column, such as Shipment[Mode] = "Ocean", is enough.',
     ref:'CALCULATE(SUM(Shipment[Revenue]), Shipment[Mode] = "Ocean")',
     alts:[{code:'CALCULATE(SUM(Shipment[Revenue]), FILTER(Shipment, Shipment[Mode] = "Ocean"))',warn:'filterInCalc'},
           {code:'CALCULATE(SUM(Shipment[Revenue]), KEEPFILTERS(Shipment[Mode] = "Ocean"))'},
           {code:'CALCULATE([Total Revenue], Shipment[Mode] = "Ocean")'},
           {code:'SUMX(FILTER(Shipment, Shipment[Mode] = "Ocean"), Shipment[Revenue])'}],
     wrongs:[{code:'SUM(Shipment[Revenue])'},{code:'CALCULATE(SUM(Shipment[Revenue]), Shipment[Mode] = "Air")'}],
     why:'CALCULATE changes the filter context: Shipment[Mode] = "Ocean" replaces any existing Mode filter, while the Region filter from the visual is kept.',
     oracle:(D,c)=>H.sumOrNull(H.vis(D,c,{drop:['Shipment[Mode]'],add:{'Shipment[Mode]':['Ocean']}}),s=>s.Revenue)},
    {id:'T04-02',v1:'i4',level:'Intermediate',title:'Key-Segment Revenue',by:['Shipment[Mode]'],checks:['slash','unqual','filterInCalc'],
     prompt:'Total revenue from customers whose Segment is "Key". Segment lives on the Customer table, not on Shipment.',
     hint:'A filter on Customer[Segment] flows down the relationship to Shipment. CALCULATE(SUM(...), Customer[Segment] = "Key").',
     ref:'CALCULATE(SUM(Shipment[Revenue]), Customer[Segment] = "Key")',
     alts:[{code:'CALCULATE(SUM(Shipment[Revenue]), FILTER(Customer, Customer[Segment] = "Key"))'},
           {code:'CALCULATE([Total Revenue], Customer[Segment] = "Key")'},
           {code:'SUMX(FILTER(Shipment, RELATED(Customer[Segment]) = "Key"), Shipment[Revenue])'}],
     wrongs:[{code:'SUM(Shipment[Revenue])'},{code:'CALCULATE(SUM(Shipment[Revenue]), Customer[Segment] = "Standard")'}],
     why:'Filters on a dimension (Customer) propagate to the fact table (Shipment) through the many-to-one relationship.',
     oracle:(D,c)=>H.sumOrNull(H.vis(D,c,{add:{'Customer[Segment]':['Key']}}),s=>s.Revenue)},
    {id:'T04-03',v1:'p1',level:'Pro',title:'Revenue per FFE',by:['Shipment[Mode]'],checks:['slash','unqual','ffeScope'],
     prompt:'Revenue per FFE (Revenue divided by Ffe). Air shipments carry revenue but have Ffe = 0 because FFE is an ocean-container unit, so they must not be counted.',
     hint:'Scope the whole ratio to shipments with Ffe > 0: CALCULATE(DIVIDE(...), KEEPFILTERS(Shipment[Ffe] > 0)).',
     ref:'CALCULATE(DIVIDE(SUM(Shipment[Revenue]), SUM(Shipment[Ffe])), KEEPFILTERS(Shipment[Ffe] > 0))',
     alts:[{code:'CALCULATE(DIVIDE(SUM(Shipment[Revenue]), SUM(Shipment[Ffe])), Shipment[Ffe] > 0)'},
           {code:'DIVIDE(CALCULATE(SUM(Shipment[Revenue]), Shipment[Ffe] > 0), SUM(Shipment[Ffe]))'}],
     wrongs:[{code:'DIVIDE(SUM(Shipment[Revenue]), SUM(Shipment[Ffe]))',warn:'ffeScope'},
             {code:'DIVIDE(SUM(Shipment[Revenue]), COUNTROWS(Shipment))'}],
     why:'The naive DIVIDE(SUM(Revenue), SUM(Ffe)) keeps Air revenue in the numerator while Air adds nothing to the denominator, which inflates the ratio. Wrapping in CALCULATE(..., KEEPFILTERS(Shipment[Ffe] > 0)) removes the Ffe = 0 rows from both parts. KEEPFILTERS intersects with any Ffe filter already in the context instead of overwriting it.',
     oracle:(D,c)=>{const r=H.vis(D,c).filter(s=>s.Ffe>0);return H.div(H.sum(r,s=>s.Revenue),H.sum(r,s=>s.Ffe));}},
    {id:'T04-04',v1:'p2',level:'Pro',title:'Key-Customer Margin %',by:['Shipment[Mode]'],checks:['slash','unqual','avgRatio'],
     prompt:'Margin % ((Revenue - Cost) / Revenue) for Key-segment customers only, as a ratio of totals, not an average of per-shipment margins.',
     hint:'Compute both the profit and the revenue under Customer[Segment] = "Key" (CALCULATE or VAR), then DIVIDE.',
     ref:'DIVIDE(\n  CALCULATE(SUM(Shipment[Revenue]) - SUM(Shipment[Cost]), Customer[Segment] = "Key"),\n  CALCULATE(SUM(Shipment[Revenue]), Customer[Segment] = "Key")\n)',
     alts:[{code:'VAR Rev = CALCULATE(SUM(Shipment[Revenue]), Customer[Segment] = "Key")\nVAR Cost = CALCULATE(SUM(Shipment[Cost]), Customer[Segment] = "Key")\nRETURN DIVIDE(Rev - Cost, Rev)'},
           {code:'CALCULATE(DIVIDE(SUM(Shipment[Revenue]) - SUM(Shipment[Cost]), SUM(Shipment[Revenue])), Customer[Segment] = "Key")'},
           {code:'CALCULATE(DIVIDE([Profit], [Total Revenue]), Customer[Segment] = "Key")'}],
     wrongs:[{code:'AVERAGEX(FILTER(Shipment, RELATED(Customer[Segment]) = "Key"), DIVIDE(Shipment[Revenue] - Shipment[Cost], Shipment[Revenue]))',warn:'avgRatio'},
             {code:'DIVIDE(SUM(Shipment[Revenue]) - SUM(Shipment[Cost]), SUM(Shipment[Revenue]))'}],
     why:'Filter first, then divide totals. AVERAGEX over per-row margins weights a small shipment the same as a large one.',
     oracle:(D,c)=>{const r=H.vis(D,c,{add:{'Customer[Segment]':['Key']}});const rev=H.sum(r,s=>s.Revenue);return H.div(rev-H.sum(r,s=>s.Cost),rev);}}
  ]
});
