"use strict";
/* Topic 5 - Removing filters. */
(function(){
  const REV=s=>s.Revenue;
  const rev=(D,c,o)=>H.sumOrNull(H.vis(D,c,o),REV);
  // context with the row's own filters removed but the report slicers kept (what ALLSELECTED restores)
  const slicerOnly=(c,keep)=>{const sel={};Object.keys(c.sel||{}).forEach(k=>{if(keep&&keep.includes(k))sel[k]=c.sel[k];});return {slicers:c.slicers,sel:sel};};

  registerTopic({
    id:'T05',title:'Removing filters',order:5,
    concept:[
      'To compare a row with a total you must remove filters inside CALCULATE. `ALL(Shipment[Mode])` (or `REMOVEFILTERS`) clears one column, `ALL(Shipment)` clears the whole table, `ALLEXCEPT(Customer, Customer[Country])` clears everything on the table except the listed columns. `ALLSELECTED` clears only the visual\'s own row filters but keeps the report slicers, so it gives "% of what the user selected".',
      '',
      '  % of All Modes = DIVIDE([Total Revenue], CALCULATE([Total Revenue], ALL(Shipment[Mode])))',
      '  % of Visible = DIVIDE([Total Revenue], CALCULATE([Total Revenue], ALLSELECTED(Shipment[Mode])))',
      '',
      'Remove only what the question needs: ALL(Shipment) is often more than you want.'
    ].join('\n'),
    challenges:[
      {id:'T05-01',level:'Beginner',title:'Company revenue on every row',by:['Shipment[Mode]'],checks:['slash','unqual'],
       prompt:'The table lists one row per Mode. On every row (and the total) show the revenue of the whole company, all modes together, so each row displays the same number.',
       hint:'Wrap the measure in CALCULATE and give it ALL(...) as a filter to throw away the Mode filter of the row.',
       ref:'CALCULATE([Total Revenue], ALL(Shipment))',
       alts:[{code:'CALCULATE(SUM(Shipment[Revenue]), ALL(Shipment))'},{code:'CALCULATE([Total Revenue], ALL(Shipment[Mode]))'},{code:'CALCULATE([Total Revenue], REMOVEFILTERS(Shipment))'}],
       wrongs:[{code:'[Total Revenue]'},
               {code:'CALCULATE([Total Revenue], ALL(Shipment[Region]))'}],
       why:'Each row of the table filters Shipment to one Mode. ALL removes that filter inside CALCULATE, so the measure sees every shipment. Clearing a different column (Region) changes nothing because the row is filtered on Mode, not Region.',
       oracle:(D,c)=>rev(D,c,{drop:['Shipment']})},
      {id:'T05-02',level:'Beginner',title:'Shipments across all regions',by:['Shipment[Region]'],checks:['slash','unqual'],
       prompt:'One row per Region. In every row show the number of shipments in all regions together, so each row shows the same count. Use REMOVEFILTERS (ALL also works).',
       hint:'CALCULATE(COUNTROWS(Shipment), REMOVEFILTERS(<the column the rows are split by>)).',
       ref:'CALCULATE(COUNTROWS(Shipment), REMOVEFILTERS(Shipment[Region]))',
       alts:[{code:'CALCULATE(COUNTROWS(Shipment), ALL(Shipment[Region]))'},{code:'CALCULATE([Shipments], REMOVEFILTERS(Shipment[Region]))'}],
       wrongs:[{code:'COUNTROWS(Shipment)'},
               {code:'CALCULATE(COUNTROWS(Shipment), REMOVEFILTERS(Shipment[Mode]))'}],
       why:'REMOVEFILTERS and ALL(column) do the same job inside CALCULATE: they clear the filter on that column. REMOVEFILTERS reads more clearly because it says exactly what it does. Removing the Mode filter is useless here, since the rows are split by Region.',
       oracle:(D,c)=>H.vis(D,c,{drop:['Shipment[Region]']}).length},
      {id:'T05-03',v1:'i5',level:'Intermediate',title:'Revenue Share of All Modes',by:['Shipment[Mode]'],checks:['slash','unqual','allTable'],
       prompt:'Each Mode\'s revenue as a share of the revenue of ALL modes. In a Mode row the denominator must ignore the Mode filter.',
       hint:'The denominator needs CALCULATE(SUM(...), ALL(Shipment[Mode])) to remove only the Mode filter.',
       ref:'DIVIDE(SUM(Shipment[Revenue]), CALCULATE(SUM(Shipment[Revenue]), ALL(Shipment[Mode])))',
       alts:[{code:'DIVIDE(SUM(Shipment[Revenue]), CALCULATE(SUM(Shipment[Revenue]), REMOVEFILTERS(Shipment[Mode])))'},
             {code:'DIVIDE([Total Revenue], CALCULATE([Total Revenue], ALL(Shipment[Mode])))'},
             {code:'DIVIDE(SUM(Shipment[Revenue]), CALCULATE(SUM(Shipment[Revenue]), ALL(Shipment)))',warn:'allTable'},
             {code:'SUM(Shipment[Revenue]) / CALCULATE(SUM(Shipment[Revenue]), ALL(Shipment[Mode]))',warn:'slash'}],
       wrongs:[{code:'DIVIDE(SUM(Shipment[Revenue]), SUM(Shipment[Revenue]))'},
               {code:'DIVIDE(SUM(Shipment[Revenue]), CALCULATE(SUM(Shipment[Revenue]), Shipment[Mode] = "Ocean"))'}],
       why:'ALL(Shipment[Mode]) removes the Mode filter from the denominator only, so each row is divided by the grand total.',
       oracle:(D,c)=>{const num=rev(D,c);const den=rev(D,c,{drop:['Shipment[Mode]']});return H.div(num,den);}},
      {id:'T05-04',level:'Intermediate',title:'Revenue of the customer\'s whole Country',by:['Customer[Country]','Customer[CustomerName]'],checks:['slash','unqual'],
       prompt:'The table lists Countries, and under each Country its customers. In a customer row show the revenue of that customer\'s whole Country (all customers of the same Country together). Country rows show their own revenue.',
       hint:'You want to clear every Customer filter except Country. ALLEXCEPT(Customer, Customer[Country]) does exactly that.',
       ref:'CALCULATE([Total Revenue], ALLEXCEPT(Customer, Customer[Country]))',
       alts:[{code:'CALCULATE([Total Revenue], REMOVEFILTERS(Customer[CustomerName]))'},{code:'CALCULATE([Total Revenue], ALL(Customer[CustomerName]))'}],
       wrongs:[{code:'[Total Revenue]'},
               {code:'CALCULATE([Total Revenue], ALL(Customer))'}],
       why:'ALLEXCEPT keeps the filters on the columns you list and clears all the others on that table. In a customer row it clears the customer-name filter but keeps Country, so the measure sees the whole Country. ALL(Customer) would clear the Country filter too.',
       oracle:(D,c)=>rev(D,c,{drop:['Customer[CustomerName]']})},
      {id:'T05-05',level:'Intermediate',title:'Share of the company total (Region and Mode)',by:['Shipment[Region]','Shipment[Mode]'],checks:['slash','unqual'],
       prompt:'The table lists Regions, and under each Region its Modes. In every row show the revenue as a percentage of the revenue of the whole company, so every Mode row is a share of the company total (not of its Region), and the grand total row shows 100%.',
       hint:'The denominator must ignore both the Region and the Mode filters. One ALL on the whole table does that.',
       ref:'DIVIDE([Total Revenue], CALCULATE([Total Revenue], ALL(Shipment)))',
       alts:[{code:'DIVIDE(SUM(Shipment[Revenue]), CALCULATE(SUM(Shipment[Revenue]), REMOVEFILTERS(Shipment)))'},
             {code:'DIVIDE([Total Revenue], CALCULATE([Total Revenue], ALL(Shipment[Region], Shipment[Mode])))'}],
       wrongs:[{code:'DIVIDE([Total Revenue], CALCULATE([Total Revenue], ALL(Shipment[Mode])))'},
               {code:'DIVIDE([Total Revenue], CALCULATE([Total Revenue], ALL(Shipment[Region])))'}],
       why:'To get a share of the grand total in a two-level table the denominator must clear both levels. Clearing only Mode gives a share of the Region (a "% of parent"), clearing only Region gives a share of the Mode.',
       oracle:(D,c)=>H.div(rev(D,c),rev(D,c,{drop:['Shipment']}))},
      {id:'T05-06',level:'Intermediate',title:'Share of the selected regions (ALLSELECTED)',by:['Shipment[Region]'],slicer:[{col:'Shipment[Region]',vals:['Asia','Europe']}],checks:['slash','unqual'],
       prompt:'A report slicer has limited the report to the regions Asia and Europe. One row per Region. Show each Region\'s revenue as a percentage of the revenue of the regions that are selected in the slicer, so the visible rows add up to 100%.',
       hint:'ALL(Shipment[Region]) would also bring back Americas. You need the denominator to respect the slicer but ignore the row: ALLSELECTED.',
       ref:'DIVIDE([Total Revenue], CALCULATE([Total Revenue], ALLSELECTED(Shipment[Region])))',
       alts:[{code:'DIVIDE(SUM(Shipment[Revenue]), CALCULATE(SUM(Shipment[Revenue]), ALLSELECTED(Shipment)))'},
             {code:'DIVIDE([Total Revenue], CALCULATE([Total Revenue], ALLSELECTED(Shipment[Region])))'}],
       wrongs:[{code:'DIVIDE([Total Revenue], CALCULATE([Total Revenue], ALL(Shipment[Region])))'},
               {code:'DIVIDE([Total Revenue], [Total Revenue])'}],
       why:'ALL removes every filter on the column, including the slicer, so the shares are measured against the whole company (Americas included) and do not add up to 100%. ALLSELECTED removes only the filter that comes from the row and restores the slicer selection.',
       oracle:(D,c)=>H.div(rev(D,c),H.sumOrNull(H.vis(D,slicerOnly(c)),REV))},
      {id:'T05-07',level:'Pro',title:'Share of parent with ISINSCOPE',by:['Customer[Segment]','Customer[CustomerName]'],checks:['slash','unqual'],
       prompt:'The table lists customer Segments, and under each Segment its customers. A customer row shows its revenue as a percentage of its Segment\'s revenue. A Segment row shows its revenue as a percentage of the company total. The grand total row shows 100%.',
       hint:'Use IF(ISINSCOPE(Customer[CustomerName]), ...) to detect a customer row. There the denominator clears only the customer name; on the other rows it clears the whole Customer table.',
       ref:'IF(\n    ISINSCOPE(Customer[CustomerName]),\n    DIVIDE([Total Revenue], CALCULATE([Total Revenue], ALL(Customer[CustomerName]))),\n    DIVIDE([Total Revenue], CALCULATE([Total Revenue], ALL(Customer)))\n)',
       alts:[{code:'IF(\n    ISINSCOPE(Customer[CustomerName]),\n    DIVIDE([Total Revenue], CALCULATE([Total Revenue], ALLEXCEPT(Customer, Customer[Segment]))),\n    DIVIDE([Total Revenue], CALCULATE([Total Revenue], REMOVEFILTERS(Customer)))\n)'}],
       wrongs:[{code:'DIVIDE([Total Revenue], CALCULATE([Total Revenue], ALL(Customer[CustomerName])))'},
               {code:'DIVIDE([Total Revenue], CALCULATE([Total Revenue], ALL(Customer)))'}],
       why:'"Percent of parent" needs a different denominator at each level. ISINSCOPE tells the measure which level the current row belongs to. Clearing only the customer name gives 100% on Segment rows; clearing the whole table everywhere gives customer shares of the company, not of the Segment.',
       oracle:(D,c)=>{const num=rev(D,c);return H.div(num,rev(D,c,{drop:[c.level===2?'Customer[CustomerName]':'Customer']}));}},
      {id:'T05-08',level:'Pro',title:'Share of Region within the selected modes',by:['Shipment[Region]','Shipment[Mode]'],slicer:[{col:'Shipment[Mode]',vals:['Ocean','Air']}],checks:['slash','unqual'],
       prompt:'A slicer limits the report to the Modes Ocean and Air. The table lists Regions, and under each Region its Modes. In a Mode row show its revenue as a percentage of its Region\'s revenue counting only the selected Modes. Region rows and the grand total show 100%.',
       hint:'Clear only the Mode filter that comes from the row, but keep the slicer: ALLSELECTED(Shipment[Mode]). The Region filter stays, so the denominator is the Region\'s total.',
       ref:'DIVIDE([Total Revenue], CALCULATE([Total Revenue], ALLSELECTED(Shipment[Mode])))',
       alts:[{code:'DIVIDE(SUM(Shipment[Revenue]), CALCULATE(SUM(Shipment[Revenue]), ALLSELECTED(Shipment[Mode])))'}],
       wrongs:[{code:'DIVIDE([Total Revenue], CALCULATE([Total Revenue], ALL(Shipment[Mode])))'},
               {code:'DIVIDE([Total Revenue], CALCULATE([Total Revenue], ALLSELECTED(Shipment)))'}],
       why:'ALL(Shipment[Mode]) also removes the slicer, so Road would be added back into the Region total. ALLSELECTED(Shipment) removes the Region filter as well, which turns the share into a share of the whole selection. ALLSELECTED(Shipment[Mode]) clears just the row\'s Mode and keeps the slicer and the Region.',
       oracle:(D,c)=>{const keep=Object.keys(c.sel||{}).filter(k=>k!=='Shipment[Mode]');return H.div(rev(D,c),H.sumOrNull(H.vis(D,slicerOnly(c,keep)),REV));}},
      {id:'T05-09',v1:'p4',level:'Pro',title:'Revenue per Shipment vs Overall',by:['Shipment[Mode]'],checks:['slash','unqual'],
       prompt:'Average revenue per shipment in the current selection minus the average revenue per shipment across ALL shipments. Use VAR / RETURN.',
       hint:'VAR CurrentAvg = AVERAGE(...)  VAR OverallAvg = CALCULATE(AVERAGE(...), ALL(Shipment))  RETURN CurrentAvg - OverallAvg',
       ref:'VAR CurrentAvg = AVERAGE(Shipment[Revenue])\nVAR OverallAvg = CALCULATE(AVERAGE(Shipment[Revenue]), ALL(Shipment))\nRETURN CurrentAvg - OverallAvg',
       alts:[{code:'AVERAGE(Shipment[Revenue]) - CALCULATE(AVERAGE(Shipment[Revenue]), ALL(Shipment))'}],
       wrongs:[{code:'AVERAGE(Shipment[Revenue])'},
               {code:'VAR CurrentAvg = AVERAGE(Shipment[Revenue])\nVAR OverallAvg = AVERAGE(Shipment[Revenue])\nRETURN CurrentAvg - OverallAvg'}],
       why:'VAR values are fixed where they are defined. OverallAvg needs ALL(Shipment) to ignore the current Mode; without it both VARs are the same number and the difference is always 0.',
       oracle:(D,c)=>{const cur=H.vis(D,c),all=H.vis(D,c,{drop:['Shipment']});if(!cur.length||!all.length)return null;return H.sum(cur,s=>s.Revenue)/cur.length-H.sum(all,s=>s.Revenue)/all.length;}}
    ]
  });
})();
