"use strict";
/* Topic 6 - FILTER & table functions. */
(function(){
  const REV=s=>s.Revenue;
  const distinct=(rows,f)=>new Set(rows.map(f)).size;

  registerTopic({
    id:'T06',title:'FILTER & table functions',order:6,
    concept:[
      '`FILTER(table, condition)` returns the rows of a table for which a condition holds; the condition may use several columns or calculated values, which a plain True/False argument of CALCULATE cannot. Table functions return tables, so wrap them in an aggregation: `COUNTROWS(FILTER(...))`, `SUMX(FILTER(...), ...)`. `VALUES(col)` and `DISTINCT(col)` list the distinct values visible in the current context; `ADDCOLUMNS`, `SUMMARIZE` and `CALCULATETABLE` build and reshape tables.',
      '',
      '  High Profit Shipments = COUNTROWS(FILTER(Shipment, Shipment[Revenue] - Shipment[Cost] > 1000))',
      '  Active Customers = COUNTROWS(VALUES(Shipment[CustomerKey]))',
      '',
      'Prefer a simple column filter in CALCULATE when one column is enough; FILTER iterates the whole table.'
    ].join('\n'),
    challenges:[
      {id:'T06-01',level:'Beginner',title:'Shipments worth more than 5,000',by:['Shipment[Mode]'],checks:['slash','unqual'],
       prompt:'Count the shipments whose revenue is greater than 5,000. Build the list of those shipments with FILTER and count its rows.',
       hint:'COUNTROWS(FILTER(Shipment, <condition on Shipment[Revenue]>)).',
       ref:'COUNTROWS(FILTER(Shipment, Shipment[Revenue] > 5000))',
       alts:[{code:'CALCULATE(COUNTROWS(Shipment), Shipment[Revenue] > 5000)'},
             {code:'COUNTX(FILTER(Shipment, Shipment[Revenue] > 5000), Shipment[ShipmentID])'}],
       wrongs:[{code:'COUNTROWS(Shipment)'},
               {code:'SUMX(FILTER(Shipment, Shipment[Revenue] > 5000), Shipment[Revenue])'}],
       why:'FILTER returns the rows of Shipment that pass the test (within the current Mode). COUNTROWS counts them. Summing the revenue of those rows would answer a different question: how much money, not how many shipments.',
       oracle:(D,c)=>H.vis(D,c).filter(s=>s.Revenue>5000).length},
      {id:'T06-02',level:'Beginner',title:'Customers that shipped (COUNTROWS of VALUES)',by:['Shipment[Mode]'],checks:['slash','unqual'],
       prompt:'How many different customers have at least one shipment? Count the rows of the list of customer keys visible in each Mode. (Not all customers use every Mode.)',
       hint:'VALUES(Shipment[CustomerKey]) is the list of customer keys left by the current filters. COUNTROWS counts that list.',
       ref:'COUNTROWS(VALUES(Shipment[CustomerKey]))',
       alts:[{code:'DISTINCTCOUNT(Shipment[CustomerKey])'},{code:'COUNTROWS(DISTINCT(Shipment[CustomerKey]))'}],
       wrongs:[{code:'COUNTROWS(Customer)'},
               {code:'COUNTROWS(Shipment)'}],
       why:'VALUES returns only the keys that survive the current filters, so each Mode counts its own customers. COUNTROWS(Customer) is 15 on every row because a filter on Shipment does not travel up to the Customer table.',
       oracle:(D,c)=>distinct(H.vis(D,c),s=>s.CustomerKey)},
      {id:'T06-03',v1:'p3',level:'Intermediate',title:'High-Profit Shipments',by:['Shipment[Mode]'],checks:['slash','unqual','filterInCalc'],
       prompt:P=>'Count shipments whose profit (Revenue - Cost) is greater than '+P.T+'.',
       hint:'The condition uses two columns, so a simple CALCULATE true/false filter will not do. Count the rows of FILTER(Shipment, ...), or sum an IF.',
       ref:P=>'COUNTROWS(FILTER(Shipment, Shipment[Revenue] - Shipment[Cost] > '+P.T+'))',
       alts:P=>[{code:'SUMX(Shipment, IF(Shipment[Revenue] - Shipment[Cost] > '+P.T+', 1, 0))'},
                {code:'COUNTX(FILTER(Shipment, Shipment[Revenue] - Shipment[Cost] > '+P.T+'), Shipment[ShipmentID])'}],
       wrongs:P=>[{code:'COUNTROWS(FILTER(Shipment, Shipment[Revenue] - Shipment[Cost] >= '+P.T+'))'},
                  {code:'CALCULATE(COUNTROWS(Shipment), Shipment[Revenue] > '+P.T+')'}],
       why:'The test is on a calculated value (Revenue - Cost), so evaluate it row by row with FILTER over the table. The condition is strictly greater than, not greater-or-equal.',
       oracle:(D,c)=>H.vis(D,c).filter(s=>s.Revenue-s.Cost>c.P.T).length},
      {id:'T06-04',level:'Intermediate',title:'Late shipments with CALCULATETABLE',by:['Shipment[Region]'],checks:['slash','unqual'],
       prompt:'How many shipments arrived late (IsOnTime = 0)? Do it by counting the rows of a table built with CALCULATETABLE.',
       hint:'CALCULATETABLE(Shipment, <filter>) is the table version of CALCULATE: it returns the Shipment rows left after applying the filter.',
       ref:'COUNTROWS(CALCULATETABLE(Shipment, Shipment[IsOnTime] = 0))',
       alts:[{code:'CALCULATE(COUNTROWS(Shipment), Shipment[IsOnTime] = 0)'},
             {code:'COUNTROWS(FILTER(Shipment, Shipment[IsOnTime] = 0))'}],
       wrongs:[{code:'COUNTROWS(Shipment)'},
               {code:'COUNTROWS(CALCULATETABLE(Shipment, Shipment[IsOnTime] = 1))'}],
       why:'CALCULATETABLE changes the filter context and returns a table instead of a single value. COUNTROWS then counts the late shipments within each Region. IsOnTime = 1 would count the on-time ones.',
       oracle:(D,c)=>H.vis(D,c).filter(s=>s.IsOnTime===0).length},
      {id:'T06-05',level:'Intermediate',title:'Customer and region combinations (SUMMARIZE)',by:['Shipment[Mode]'],checks:['slash','unqual'],
       prompt:'Count the distinct combinations of customer and Region that have shipments. A customer who ships to Asia and to Europe counts as 2. Build the list of combinations with SUMMARIZE and count its rows.',
       hint:'SUMMARIZE(Shipment, Shipment[CustomerKey], Shipment[Region]) returns one row for each combination that exists.',
       ref:'COUNTROWS(SUMMARIZE(Shipment, Shipment[CustomerKey], Shipment[Region]))',
       alts:[{code:'COUNTROWS(SUMMARIZE(Shipment, Customer[CustomerName], Shipment[Region]))'},
             {code:'SUMX(VALUES(Shipment[Region]), CALCULATE(DISTINCTCOUNT(Shipment[CustomerKey])))'}],
       wrongs:[{code:'DISTINCTCOUNT(Shipment[CustomerKey])'},
               {code:'COUNTROWS(Shipment)'}],
       why:'SUMMARIZE groups the shipments by the columns you name and returns one row per group. Counting only distinct customers ignores the Region part, and counting shipments counts a customer-and-region pair again for every shipment it has.',
       oracle:(D,c)=>distinct(H.vis(D,c),s=>s.CustomerKey+'|'+s.Region)},
      {id:'T06-06',level:'Intermediate',title:'Best single-shipment margin (ADDCOLUMNS)',by:['Shipment[Mode]'],checks:['slash','unqual','avgRatio'],
       prompt:'The highest profit margin of any single shipment, where margin = (Revenue - Cost) / Revenue. Add a margin column to the Shipment table with ADDCOLUMNS and take its maximum.',
       hint:'MAXX(ADDCOLUMNS(Shipment, "Margin", <formula>), [Margin]).',
       ref:'MAXX(\n    ADDCOLUMNS(Shipment, "Margin", DIVIDE(Shipment[Revenue] - Shipment[Cost], Shipment[Revenue])),\n    [Margin]\n)',
       alts:[{code:'MAXX(Shipment, DIVIDE(Shipment[Revenue] - Shipment[Cost], Shipment[Revenue]))'}],
       wrongs:[{code:'DIVIDE([Profit], [Total Revenue])'},
               {code:'AVERAGEX(Shipment, DIVIDE(Shipment[Revenue] - Shipment[Cost], Shipment[Revenue]))',warn:'avgRatio'}],
       why:'ADDCOLUMNS returns the same table with extra calculated columns, and MAXX then takes the maximum of one of them. The overall margin (profit / revenue of the whole Mode) is a single blended ratio, not the best shipment.',
       oracle:(D,c)=>{const r=H.vis(D,c);return r.length?Math.max.apply(null,r.map(s=>(s.Revenue-s.Cost)/s.Revenue)):null;}},
      {id:'T06-07',level:'Pro',title:'Revenue of above-average shipments',by:['Shipment[Mode]'],checks:['slash','unqual'],
       prompt:'Total revenue of the shipments that are bigger than the average shipment of the same Mode (revenue greater than the Mode\'s average shipment revenue). Shipments at or below the average are left out.',
       hint:'Compute the average once in a VAR, then SUMX(FILTER(Shipment, Shipment[Revenue] > that VAR), Shipment[Revenue]). Inside FILTER an aggregation still sees the Mode of the row.',
       ref:'VAR AvgRev = AVERAGE(Shipment[Revenue])\nRETURN\n    SUMX(FILTER(Shipment, Shipment[Revenue] > AvgRev), Shipment[Revenue])',
       alts:[{code:'SUMX(FILTER(Shipment, Shipment[Revenue] > AVERAGE(Shipment[Revenue])), Shipment[Revenue])'}],
       wrongs:[{code:'SUMX(FILTER(Shipment, Shipment[Revenue] > CALCULATE(AVERAGE(Shipment[Revenue]))), Shipment[Revenue])'},
               {code:'SUMX(FILTER(ALL(Shipment), Shipment[Revenue] > AVERAGE(Shipment[Revenue])), Shipment[Revenue])'}],
       why:'AVERAGE inside FILTER is evaluated in the filter context of the row (the Mode), so it is the Mode\'s average. Wrapping it in CALCULATE turns each shipment into a filter, so the "average" becomes that shipment\'s own revenue and nothing is greater than itself. FILTER(ALL(Shipment), ...) compares every shipment of the company with the Mode\'s average.',
       oracle:(D,c)=>{const r=H.vis(D,c);if(!r.length)return null;const a=H.sum(r,REV)/r.length;return H.sumOrNull(r.filter(s=>s.Revenue>a),REV);}},
      {id:'T06-08',level:'Pro',title:'Customers over 100,000 (ADDCOLUMNS + FILTER)',by:['Shipment[Mode]'],checks:['slash','unqual'],
       prompt:'How many customers have revenue greater than 100,000 in the current Mode? Build a table of the visible customers with a revenue column (ADDCOLUMNS), keep the big ones with FILTER, and count the rows.',
       hint:'ADDCOLUMNS(VALUES(Shipment[CustomerKey]), "CustRev", [Total Revenue]) gives one revenue figure per customer. Then FILTER on [CustRev].',
       ref:'COUNTROWS(\n    FILTER(\n        ADDCOLUMNS(VALUES(Shipment[CustomerKey]), "CustRev", [Total Revenue]),\n        [CustRev] > 100000\n    )\n)',
       alts:[{code:'COUNTROWS(FILTER(VALUES(Shipment[CustomerKey]), [Total Revenue] > 100000))'}],
       wrongs:[{code:'COUNTROWS(FILTER(ADDCOLUMNS(VALUES(Shipment[CustomerKey]), "CustRev", SUM(Shipment[Revenue])), [CustRev] > 100000))'},
               {code:'DISTINCTCOUNT(Shipment[CustomerKey])'}],
       why:'Referring to a measure inside ADDCOLUMNS evaluates it once per customer (a measure reference has a hidden CALCULATE). A bare SUM does not: every customer row would receive the same Mode total, so either all customers or none pass the test.',
       oracle:(D,c)=>H.byCustomer(H.vis(D,c),REV).filter(x=>x.val>100000).length},
      {id:'T06-09',level:'Pro',title:'Average revenue per customer-month (SUMMARIZE)',by:['Shipment[Mode]'],checks:['slash','unqual'],
       prompt:'Group the shipments by customer and month (Date[YearMonth]); each group is one "customer-month". Show the average revenue of a customer-month in the current Mode.',
       hint:'AVERAGEX(SUMMARIZE(Shipment, Shipment[CustomerKey], Date[YearMonth]), <revenue of that group>). The revenue of the group needs a measure or CALCULATE.',
       ref:'AVERAGEX(\n    SUMMARIZE(Shipment, Shipment[CustomerKey], Date[YearMonth]),\n    [Total Revenue]\n)',
       alts:[{code:'AVERAGEX(SUMMARIZE(Shipment, Shipment[CustomerKey], Date[YearMonth]), CALCULATE(SUM(Shipment[Revenue])))'},
             {code:'DIVIDE(SUM(Shipment[Revenue]), COUNTROWS(SUMMARIZE(Shipment, Shipment[CustomerKey], Date[YearMonth])))'}],
       wrongs:[{code:'AVERAGE(Shipment[Revenue])'},
               {code:'AVERAGEX(SUMMARIZE(Shipment, Shipment[CustomerKey], Date[YearMonth]), SUM(Shipment[Revenue]))'}],
       why:'Each SUMMARIZE row is a customer-month; the measure inside AVERAGEX is evaluated for that group. AVERAGE(Revenue) averages single shipments, which is smaller. A bare SUM inside AVERAGEX does not switch to the group, so it just returns the whole Mode total.',
       oracle:(D,c)=>{const o={};H.vis(D,c).forEach(s=>{const k=s.CustomerKey+'|'+s._d.YearMonth;o[k]=(o[k]||0)+s.Revenue;});const v=Object.values(o);return v.length?H.sum(v,x=>x)/v.length:null;}}
    ]
  });
})();
