"use strict";
/* Topic 7 - Context transition. */
(function(){
  const REV=s=>s.Revenue;
  const custRev=(D,c)=>H.byCustomer(H.vis(D,c),REV);      // [{key,val}] revenue per customer visible on the row

  registerTopic({
    id:'T07',title:'Context transition',order:7,
    concept:[
      'Inside an iterator you have a row context (the current row), but aggregations such as `SUM` only see the filter context. `CALCULATE` converts the current row into filters, which is called context transition. A reference to a measure does the same automatically: `[Total Revenue]` is really `CALCULATE([Total Revenue])`. That is why a measure works per customer inside `SUMX(Customer, ...)` while a bare `SUM` gives the grand total for every row.',
      '',
      '  Busy Customer Revenue =',
      '      SUMX(FILTER(VALUES(Shipment[CustomerKey]), CALCULATE(COUNTROWS(Shipment)) > 25),',
      '           CALCULATE(SUM(Shipment[Revenue])))',
      '',
      'If an iterator seems to return the same number on every row, check where the transition is missing.'
    ].join('\n'),
    challenges:[
      {id:'T07-01',level:'Beginner',title:'Average revenue per customer',by:['Shipment[Mode]'],checks:['slash','unqual'],
       prompt:'The average of the customers\' total revenue: work out each customer\'s revenue in the current Mode, then average those customer totals. (Not the average per shipment.)',
       hint:'AVERAGEX(<list of customers>, <that customer\'s revenue>). A measure reference such as [Total Revenue] gives the revenue of the customer on the current row.',
       ref:'AVERAGEX(VALUES(Shipment[CustomerKey]), [Total Revenue])',
       alts:[{code:'AVERAGEX(VALUES(Shipment[CustomerKey]), CALCULATE(SUM(Shipment[Revenue])))'},
             {code:'AVERAGEX(Customer, [Total Revenue])'},
             {code:'DIVIDE([Total Revenue], DISTINCTCOUNT(Shipment[CustomerKey]))'}],
       wrongs:[{code:'AVERAGE(Shipment[Revenue])'},
               {code:'AVERAGEX(VALUES(Shipment[CustomerKey]), SUM(Shipment[Revenue]))'}],
       why:'The measure reference inside AVERAGEX runs once per customer because the customer on the current row becomes a filter. A bare SUM does not see the row, so every customer gets the same total and the "average" is just the total. AVERAGEX(Customer, ...) also works: customers without shipments return BLANK and AVERAGEX skips them.',
       oracle:(D,c)=>{const v=custRev(D,c);return v.length?H.sum(v,x=>x.val)/v.length:null;}},
      {id:'T07-02',level:'Intermediate',title:'Revenue of the best customer',by:['Shipment[Mode]'],checks:['slash','unqual'],
       prompt:'The revenue of the single biggest customer in the current Mode (the highest customer total, not the largest shipment).',
       hint:'MAXX over the customers, evaluating a total revenue measure for each one.',
       ref:'MAXX(VALUES(Shipment[CustomerKey]), [Total Revenue])',
       alts:[{code:'MAXX(VALUES(Shipment[CustomerKey]), CALCULATE(SUM(Shipment[Revenue])))'},
             {code:'MAXX(Customer, [Total Revenue])'}],
       wrongs:[{code:'MAX(Shipment[Revenue])'},
               {code:'MAXX(VALUES(Shipment[CustomerKey]), SUM(Shipment[Revenue]))'}],
       why:'MAX(Revenue) finds the largest single shipment. To find the best customer you must first total each customer (context transition) and then take the maximum of those totals.',
       oracle:(D,c)=>{const v=custRev(D,c);return v.length?Math.max.apply(null,v.map(x=>x.val)):null;}},
      {id:'T07-03',level:'Intermediate',title:'Customers with a low on-time rate',by:['Shipment[Mode]'],checks:['slash','unqual'],
       prompt:'Count the customers whose on-time rate is below 70% in the current Mode. Each customer\'s rate is its own on-time shipments divided by its own shipments.',
       hint:'COUNTROWS(FILTER(<customers>, <on-time rate of that customer> < 0.7)). The library measure [On-Time %] already gives one customer\'s rate when it is evaluated per customer.',
       ref:'COUNTROWS(FILTER(VALUES(Shipment[CustomerKey]), [On-Time %] < 0.7))',
       alts:[{code:'COUNTROWS(FILTER(VALUES(Shipment[CustomerKey]), CALCULATE(DIVIDE(SUM(Shipment[IsOnTime]), COUNTROWS(Shipment))) < 0.7))'}],
       wrongs:[{code:'COUNTROWS(FILTER(VALUES(Shipment[CustomerKey]), DIVIDE(SUM(Shipment[IsOnTime]), COUNTROWS(Shipment)) < 0.7))'},
               {code:'COUNTROWS(FILTER(Customer, [On-Time %] < 0.7))'}],
       why:'The rate must be calculated per customer, which is what the measure reference does inside FILTER. Without the transition every customer gets the Mode\'s overall rate, so all or none pass. Iterating the whole Customer table is also wrong: a customer without shipments in this Mode has a BLANK rate, and BLANK < 0.7 is TRUE in DAX, so those customers get counted too.',
       oracle:(D,c)=>{const n={},ot={};H.vis(D,c).forEach(s=>{n[s.CustomerKey]=(n[s.CustomerKey]||0)+1;ot[s.CustomerKey]=(ot[s.CustomerKey]||0)+s.IsOnTime;});return Object.keys(n).filter(k=>ot[k]/n[k]<0.7).length;}},
      {id:'T07-04',level:'Intermediate',title:'Months with revenue above 60,000',by:['Date[Year]'],checks:['slash','unqual','hardcodedPeriod'],
       prompt:'For each year, count the months in which total revenue was greater than 60,000. The grand total row counts the months of all years together.',
       hint:'Iterate the months of the row: COUNTROWS(FILTER(VALUES(Date[YearMonth]), <revenue of that month> > 60000)).',
       ref:'COUNTROWS(FILTER(VALUES(Date[YearMonth]), [Total Revenue] > 60000))',
       alts:[{code:'COUNTROWS(FILTER(VALUES(Date[YearMonth]), CALCULATE(SUM(Shipment[Revenue])) > 60000))'},
             {code:'COUNTROWS(FILTER(SUMMARIZE(Shipment, Date[YearMonth]), [Total Revenue] > 60000))'}],
       wrongs:[{code:'COUNTROWS(FILTER(VALUES(Date[YearMonth]), SUM(Shipment[Revenue]) > 60000))'},
               {code:'COUNTROWS(FILTER(VALUES(Date[Year]), [Total Revenue] > 60000))'}],
       why:'Each month on the list has to be turned into a filter before its revenue is totalled, and the measure reference does this. The bare SUM sees the whole year for every month, so the test is true for all months or for none. Iterating years instead of months answers a different question.',
       oracle:(D,c)=>{const o={};H.vis(D,c).forEach(s=>{o[s._d.YearMonth]=(o[s._d.YearMonth]||0)+s.Revenue;});return Object.values(o).filter(v=>v>60000).length;}},
      {id:'T07-05',v1:'p5',level:'Intermediate',title:'Revenue from Busy Customers',by:['Customer[Segment]'],checks:['slash','unqual'],
       prompt:P=>'Total revenue from customers with more than '+P.n+' shipments (in the current filter context). Shown by customer Segment.',
       hint:'Iterate the customers: SUMX(FILTER(VALUES(Shipment[CustomerKey]), <shipments of this customer> > n), <revenue of this customer>). Each inner measure needs CALCULATE to apply the current customer.',
       ref:P=>'SUMX(\n  FILTER(VALUES(Shipment[CustomerKey]), CALCULATE(COUNTROWS(Shipment)) > '+P.n+'),\n  CALCULATE(SUM(Shipment[Revenue]))\n)',
       alts:P=>[{code:'SUMX(FILTER(Customer, CALCULATE(COUNTROWS(Shipment)) > '+P.n+'), CALCULATE(SUM(Shipment[Revenue])))'},
                {code:'SUMX(FILTER(VALUES(Customer[CustomerKey]), CALCULATE(COUNTROWS(Shipment)) > '+P.n+'), CALCULATE(SUM(Shipment[Revenue])))'},
                {code:'SUMX(FILTER(Customer, [Shipments] > '+P.n+'), [Total Revenue])'}],
       wrongs:P=>[{code:'SUM(Shipment[Revenue])'},
                  {code:'SUMX(FILTER(VALUES(Shipment[CustomerKey]), CALCULATE(COUNTROWS(Shipment)) >= '+P.n+'), CALCULATE(SUM(Shipment[Revenue])))'},
                  {code:'SUMX(FILTER(VALUES(Shipment[CustomerKey]), COUNTROWS(Shipment) > '+P.n+'), SUM(Shipment[Revenue]))'}],
       why:'Inside an iterator, CALCULATE (or a measure reference) turns the current row (the current customer) into a filter - context transition. Without it, COUNTROWS and SUM ignore the current customer and see every shipment.',
       oracle:(D,c)=>{const rows=H.vis(D,c);const by=H.byCustomer(rows,()=>1);const cnt={};by.forEach(x=>cnt[x.key]=x.val);
         return H.sumOrNull(rows.filter(s=>cnt[s.CustomerKey]>c.P.n),s=>s.Revenue);}},
      {id:'T07-06',level:'Pro',title:'Best month of each customer',by:['Customer[CustomerName]'],checks:['slash','unqual'],
       prompt:'One row per customer. Show the revenue of that customer\'s best month: the highest monthly revenue the customer has had. The total row shows the best month of the whole company.',
       hint:'MAXX over the months (VALUES(Date[YearMonth])), evaluating the revenue measure for each month. The customer of the row stays in the filter.',
       ref:'MAXX(VALUES(Date[YearMonth]), [Total Revenue])',
       alts:[{code:'MAXX(SUMMARIZE(Shipment, Date[YearMonth]), [Total Revenue])'},
             {code:'MAXX(VALUES(Date[YearMonth]), CALCULATE(SUM(Shipment[Revenue])))'}],
       wrongs:[{code:'MAXX(VALUES(Date[YearMonth]), SUM(Shipment[Revenue]))'},
               {code:'MAX(Shipment[Revenue])'}],
       why:'For every month in the list the measure sees that month plus the customer of the row, so MAXX gets one monthly total per month and picks the largest. With a bare SUM the month never reaches the calculation and MAXX just returns the customer\'s all-time total; MAX(Revenue) is the largest single shipment.',
       oracle:(D,c)=>{const o={};H.vis(D,c).forEach(s=>{o[s._d.YearMonth]=(o[s._d.YearMonth]||0)+s.Revenue;});const v=Object.values(o);return v.length?Math.max.apply(null,v):null;}},
      {id:'T07-07',level:'Pro',title:'Revenue of above-average customers',by:['Shipment[Mode]'],checks:['slash','unqual'],
       prompt:'Compute the average revenue per customer in the current Mode. Then add up the revenue of the customers whose own revenue is greater than that average.',
       hint:'Keep the average in a VAR first, then SUMX(FILTER(<customers>, [Total Revenue] > AvgCust), [Total Revenue]).',
       ref:'VAR AvgCust = AVERAGEX(VALUES(Shipment[CustomerKey]), [Total Revenue])\nRETURN\n    SUMX(FILTER(VALUES(Shipment[CustomerKey]), [Total Revenue] > AvgCust), [Total Revenue])',
       alts:[{code:'VAR AvgCust = AVERAGEX(Customer, [Total Revenue])\nRETURN\n    SUMX(FILTER(Customer, [Total Revenue] > AvgCust), [Total Revenue])'}],
       wrongs:[{code:'VAR AvgCust = AVERAGE(Shipment[Revenue])\nRETURN\n    SUMX(FILTER(VALUES(Shipment[CustomerKey]), [Total Revenue] > AvgCust), [Total Revenue])'},
               {code:'VAR AvgCust = AVERAGEX(VALUES(Shipment[CustomerKey]), [Total Revenue])\nRETURN\n    SUMX(FILTER(VALUES(Shipment[CustomerKey]), [Total Revenue] > AvgCust), SUM(Shipment[Revenue]))'}],
       why:'The threshold has to be an average of customer totals. The average shipment is far smaller, so almost every customer would pass. In the last step the measure reference adds each customer\'s own revenue; a bare SUM would add the whole Mode total once for every qualifying customer.',
       oracle:(D,c)=>{const v=custRev(D,c);if(!v.length)return null;const a=H.sum(v,x=>x.val)/v.length;return H.sumOrNull(v.filter(x=>x.val>a),x=>x.val);}},
      {id:'T07-08',level:'Pro',title:'Customers that used two or more modes',by:['Shipment[Region]'],checks:['slash','unqual'],
       prompt:'In each Region, count the customers that shipped with at least 2 different Modes in that Region (for example both Ocean and Air).',
       hint:'For each customer you need the number of distinct Modes: CALCULATE(DISTINCTCOUNT(Shipment[Mode])) inside FILTER over the customer list.',
       ref:'COUNTROWS(FILTER(VALUES(Shipment[CustomerKey]), CALCULATE(DISTINCTCOUNT(Shipment[Mode])) >= 2))',
       alts:[{code:'COUNTROWS(FILTER(Customer, CALCULATE(DISTINCTCOUNT(Shipment[Mode])) >= 2))'}],
       wrongs:[{code:'COUNTROWS(FILTER(VALUES(Shipment[CustomerKey]), DISTINCTCOUNT(Shipment[Mode]) >= 2))'},
               {code:'COUNTROWS(FILTER(VALUES(Shipment[CustomerKey]), CALCULATE(DISTINCTCOUNT(Shipment[Mode])) > 2))'}],
       why:'The number of Modes must be counted for one customer at a time, so the count sits inside CALCULATE. Without it every customer receives the Region\'s overall count of Modes and either all customers or none qualify.',
       oracle:(D,c)=>{const m={};H.vis(D,c).forEach(s=>{(m[s.CustomerKey]=m[s.CustomerKey]||new Set()).add(s.Mode);});return Object.values(m).filter(x=>x.size>=2).length;}}
    ]
  });
})();
