"use strict";
/* Topic 8 - Logic & scope. */
(function(){
  const REV=s=>s.Revenue;
  const rev=(D,c,o)=>H.sumOrNull(H.vis(D,c,o),REV);
  const band=v=>v>=150000?'High':(v>=75000?'Medium':'Low');

  registerTopic({
    id:'T08',title:'Logic & scope',order:8,
    concept:[
      '`IF` and `SWITCH` choose a result. `SWITCH(TRUE(), cond1, result1, cond2, result2, ..., else)` is the readable way to write a ladder of conditions; the first true condition wins, so put the strictest test first. `SELECTEDVALUE(col, alternate)` returns the one value left by the filters, or the alternate when there are zero or several. `HASONEVALUE(col)` tests exactly that. `ISINSCOPE(col)` is true only on the rows of a visual that are grouped by that column, so a measure can show a different value on the total row. `COALESCE` returns its first non-blank argument.',
      '',
      '  Band = SWITCH(TRUE(), [Total Revenue] > 100000, "High", [Total Revenue] > 50000, "Medium", "Low")',
      '  Label = IF(ISINSCOPE(Customer[CustomerName]), [Total Revenue], BLANK())'
    ].join('\n'),
    challenges:[
      {id:'T08-01',level:'Beginner',title:'On target or below target',by:['Customer[CustomerName]'],checks:['slash','unqual'],
       prompt:'For each customer show the text "On target" if its on-time rate is 75% or more, otherwise "Below target".',
       hint:'IF(<condition>, "On target", "Below target"). The library measure [On-Time %] gives the rate as a fraction, 0.75 means 75%.',
       ref:'IF([On-Time %] >= 0.75, "On target", "Below target")',
       alts:[{code:'SWITCH(TRUE(), [On-Time %] >= 0.75, "On target", "Below target")'},
             {code:'IF(DIVIDE(SUM(Shipment[IsOnTime]), COUNTROWS(Shipment)) >= 0.75, "On target", "Below target")'}],
       wrongs:[{code:'IF([On-Time %] >= 0.75, "Below target", "On target")'},
               {code:'IF(SUM(Shipment[IsOnTime]) >= 0.75, "On target", "Below target")'}],
       why:'IF returns the second argument when the condition is true and the third when it is false. SUM(IsOnTime) is a count of on-time shipments (a whole number), not a rate, so comparing it with 0.75 is true for almost every customer.',
       oracle:(D,c)=>{const r=H.vis(D,c);if(!r.length)return null;return H.sum(r,s=>s.IsOnTime)/r.length>=0.75?'On target':'Below target';}},
      {id:'T08-02',level:'Beginner',title:'Show revenue only for busy customers',by:['Customer[CustomerName]'],checks:['slash','unqual'],
       prompt:P=>'For each customer show its revenue only if it has more than '+P.n+' shipments. Customers with '+P.n+' shipments or fewer should be left empty (BLANK).',
       hint:'IF(<condition>, <value>) with no third argument returns BLANK when the condition is false. The library measures [Shipments] and [Total Revenue] help.',
       ref:P=>'IF([Shipments] > '+P.n+', [Total Revenue])',
       alts:P=>[{code:'IF([Shipments] > '+P.n+', [Total Revenue], BLANK())'},
                {code:'IF(COUNTROWS(Shipment) > '+P.n+', SUM(Shipment[Revenue]), BLANK())'}],
       wrongs:P=>[{code:'IF([Shipments] >= '+P.n+', [Total Revenue])'},
                  {code:'IF([Total Revenue] > '+P.n+', [Total Revenue])'}],
       why:'The test is about the number of shipments, strictly more than the limit. A customer with exactly the limit must stay empty. Comparing the revenue with the limit would be true for everybody, because revenue is in the thousands.',
       oracle:(D,c)=>{const r=H.vis(D,c);return r.length>c.P.n?H.sum(r,REV):null;}},
      {id:'T08-03',level:'Intermediate',title:'Revenue bands with SWITCH(TRUE())',by:['Customer[CustomerName]'],checks:['slash','unqual'],
       prompt:'Give each customer a revenue band: "High" if revenue is 150,000 or more, "Medium" if it is 75,000 or more, otherwise "Low". The total row gets a band too.',
       hint:'SWITCH(TRUE(), test1, result1, test2, result2, else). SWITCH checks the tests in order and stops at the first one that is true.',
       ref:'SWITCH(\n    TRUE(),\n    [Total Revenue] >= 150000, "High",\n    [Total Revenue] >= 75000, "Medium",\n    "Low"\n)',
       alts:[{code:'IF([Total Revenue] >= 150000, "High", IF([Total Revenue] >= 75000, "Medium", "Low"))'},
             {code:'VAR Rev = [Total Revenue]\nRETURN SWITCH(TRUE(), Rev >= 150000, "High", Rev >= 75000, "Medium", "Low")'}],
       wrongs:[{code:'SWITCH(TRUE(), [Total Revenue] >= 75000, "Medium", [Total Revenue] >= 150000, "High", "Low")'},
               {code:'SWITCH(TRUE(), [Total Revenue] >= 150000, "High", [Total Revenue] >= 75000, "Medium")'}],
       why:'The first true condition wins. If the 75,000 test comes first, a 200,000 customer already matches it and is called "Medium"; the strictest test must come first. The last argument is the default; without it low customers return BLANK instead of "Low".',
       oracle:(D,c)=>{const v=rev(D,c);return v==null?null:band(v);}},
      {id:'T08-04',level:'Intermediate',title:'Segment name with a fallback',by:['Customer[Segment]'],checks:['slash','unqual'],
       prompt:'Show the name of the Segment on a Segment row. On the grand total row, where there are two Segments, show the text "All Segments" instead.',
       hint:'SELECTEDVALUE(column, alternate) returns the single value in the filter, or the alternate when there are several values.',
       ref:'SELECTEDVALUE(Customer[Segment], "All Segments")',
       alts:[{code:'IF(HASONEVALUE(Customer[Segment]), SELECTEDVALUE(Customer[Segment]), "All Segments")'},
             {code:'IF(ISINSCOPE(Customer[Segment]), SELECTEDVALUE(Customer[Segment]), "All Segments")'}],
       wrongs:[{code:'SELECTEDVALUE(Customer[Segment])'},
               {code:'"All Segments"'}],
       why:'SELECTEDVALUE returns the value only when exactly one value is visible. On the total row two Segments are visible, so without the second argument the result is BLANK; with it you choose the label.',
       oracle:(D,c)=>c.level===1?c.sel['Customer[Segment]']:'All Segments'},
      {id:'T08-05',level:'Intermediate',title:'Blank total with HASONEVALUE',by:['Shipment[Mode]'],checks:['slash','unqual'],
       prompt:'Show the revenue of each Mode, but leave the grand total row empty (BLANK), as the total is not meaningful for this report.',
       hint:'IF(HASONEVALUE(Shipment[Mode]), [Total Revenue]). HASONEVALUE is true when exactly one Mode is visible.',
       ref:'IF(HASONEVALUE(Shipment[Mode]), [Total Revenue])',
       alts:[{code:'IF(ISINSCOPE(Shipment[Mode]), [Total Revenue], BLANK())'},
             {code:'IF(COUNTROWS(VALUES(Shipment[Mode])) = 1, [Total Revenue])'}],
       wrongs:[{code:'[Total Revenue]'},
               {code:'IF(HASONEVALUE(Shipment[Region]), [Total Revenue])'}],
       why:'On a Mode row exactly one Mode is visible; on the total row all Modes are. HASONEVALUE tells the two apart. Testing a column the rows are not split by (Region) is false everywhere, so the whole column goes blank.',
       oracle:(D,c)=>c.level===1?rev(D,c):null},
      {id:'T08-06',level:'Intermediate',title:'Air revenue, or total if no Air',by:['Customer[CustomerName]'],checks:['slash','unqual'],
       prompt:'For each customer show its Air revenue. If the customer has no Air shipments (the Air revenue is BLANK), show its total revenue of all Modes instead.',
       hint:'COALESCE(first, second) returns the first argument that is not BLANK. The first is CALCULATE([Total Revenue], Shipment[Mode] = "Air").',
       ref:'COALESCE(CALCULATE([Total Revenue], Shipment[Mode] = "Air"), [Total Revenue])',
       alts:[{code:'VAR AirRev = CALCULATE([Total Revenue], Shipment[Mode] = "Air")\nRETURN IF(ISBLANK(AirRev), [Total Revenue], AirRev)'},
             {code:'IF(ISBLANK(CALCULATE([Total Revenue], Shipment[Mode] = "Air")), [Total Revenue], CALCULATE([Total Revenue], Shipment[Mode] = "Air"))'}],
       wrongs:[{code:'CALCULATE([Total Revenue], Shipment[Mode] = "Air")'},
               {code:'COALESCE([Total Revenue], CALCULATE([Total Revenue], Shipment[Mode] = "Air"))'}],
       why:'COALESCE takes the first non-blank value. Without it customers with no Air shipments show nothing. With the arguments swapped, the total revenue is never blank for a customer that shipped anything, so the Air figure is never used.',
       oracle:(D,c)=>{const a=rev(D,c,{add:{'Shipment[Mode]':['Air']}});return a!=null?a:rev(D,c);}},
      {id:'T08-07',level:'Intermediate',title:'Total row shows the target',by:['Shipment[Mode]'],checks:['slash','unqual'],
       prompt:'Each Mode row shows its on-time rate. The grand total row must show the company target of 90% (0.9) instead of the actual total rate.',
       hint:'IF(ISINSCOPE(Shipment[Mode]), <rate>, <target>). ISINSCOPE is true on rows that are split by Mode and false on the total.',
       ref:'IF(ISINSCOPE(Shipment[Mode]), [On-Time %], 0.9)',
       alts:[{code:'IF(HASONEVALUE(Shipment[Mode]), [On-Time %], 0.9)'},
             {code:'SWITCH(TRUE(), ISINSCOPE(Shipment[Mode]), [On-Time %], 0.9)'}],
       wrongs:[{code:'[On-Time %]'},
               {code:'IF(ISINSCOPE(Shipment[Region]), [On-Time %], 0.9)'}],
       why:'A measure is evaluated once per cell, and ISINSCOPE lets it know whether the cell belongs to a Mode row. The total row is not "in scope" of Mode, so it returns the target. Asking about Region, which the rows are not grouped by, is false on every row.',
       oracle:(D,c)=>c.level===1?H.div(H.sum(H.vis(D,c),s=>s.IsOnTime),H.vis(D,c).length):0.9},
      {id:'T08-08',level:'Pro',title:'Hide subtotals, keep the grand total',by:['Shipment[Region]','Shipment[Mode]'],checks:['slash','unqual'],
       prompt:'The table lists Regions, and under each Region its Modes. Show revenue on the Mode rows and on the grand total row, but leave the Region subtotal rows empty (BLANK).',
       hint:'A Region subtotal row is the one where Region is in scope but Mode is not: ISINSCOPE(Shipment[Region]) && NOT(ISINSCOPE(Shipment[Mode])).',
       ref:'IF(ISINSCOPE(Shipment[Region]) && NOT(ISINSCOPE(Shipment[Mode])), BLANK(), [Total Revenue])',
       alts:[{code:'SWITCH(TRUE(), ISINSCOPE(Shipment[Mode]), [Total Revenue], ISINSCOPE(Shipment[Region]), BLANK(), [Total Revenue])'},
             {code:'IF(ISINSCOPE(Shipment[Mode]), [Total Revenue], IF(ISINSCOPE(Shipment[Region]), BLANK(), [Total Revenue]))'}],
       wrongs:[{code:'IF(ISINSCOPE(Shipment[Mode]), [Total Revenue])'},
               {code:'SWITCH(TRUE(), ISINSCOPE(Shipment[Region]), BLANK(), [Total Revenue])'}],
       why:'In a two-level table the Mode rows have both columns in scope, the Region subtotals only Region, and the grand total neither. Testing only Mode also blanks the grand total. Testing Region first blanks the Mode rows too, since Region is in scope there as well, so order matters.',
       oracle:(D,c)=>c.level===1?null:rev(D,c)},
      {id:'T08-09',level:'Pro',title:'One label column for a two-level table',by:['Customer[Segment]','Customer[CustomerName]'],checks:['slash','unqual'],
       prompt:'The table lists Segments, and under each Segment its customers. A customer row shows its revenue band: "High" for 150,000 or more, "Medium" for 75,000 or more, otherwise "Low". A Segment row shows the text "Segment: " followed by the Segment name (for example Segment: Key). The grand total row shows "All customers".',
       hint:'Use SWITCH(TRUE(), ...) with ISINSCOPE tests: customer level first, then Segment level, then the default. Put the revenue in a VAR. Join text with &.',
       ref:'VAR Rev = [Total Revenue]\nRETURN\n    SWITCH(\n        TRUE(),\n        ISINSCOPE(Customer[CustomerName]), SWITCH(TRUE(), Rev >= 150000, "High", Rev >= 75000, "Medium", "Low"),\n        ISINSCOPE(Customer[Segment]), "Segment: " & SELECTEDVALUE(Customer[Segment]),\n        "All customers"\n    )',
       alts:[{code:'VAR Rev = [Total Revenue]\nRETURN\n    IF(\n        ISINSCOPE(Customer[CustomerName]),\n        IF(Rev >= 150000, "High", IF(Rev >= 75000, "Medium", "Low")),\n        IF(ISINSCOPE(Customer[Segment]), "Segment: " & SELECTEDVALUE(Customer[Segment]), "All customers")\n    )'}],
       wrongs:[{code:'VAR Rev = [Total Revenue]\nRETURN\n    SWITCH(\n        TRUE(),\n        ISINSCOPE(Customer[Segment]), "Segment: " & SELECTEDVALUE(Customer[Segment]),\n        ISINSCOPE(Customer[CustomerName]), SWITCH(TRUE(), Rev >= 150000, "High", Rev >= 75000, "Medium", "Low"),\n        "All customers"\n    )'},
               {code:'VAR Rev = [Total Revenue]\nRETURN\n    SWITCH(\n        TRUE(),\n        ISINSCOPE(Customer[CustomerName]), SWITCH(TRUE(), Rev >= 75000, "Medium", Rev >= 150000, "High", "Low"),\n        ISINSCOPE(Customer[Segment]), "Segment: " & SELECTEDVALUE(Customer[Segment]),\n        "All customers"\n    )'}],
       why:'On a customer row both Customer and Segment are in scope, so the customer test has to come first or the Segment label would win everywhere. Inside the customer branch the band tests must again go from the highest threshold to the lowest.',
       oracle:(D,c)=>{if(c.level===2){const v=rev(D,c);return v==null?null:band(v);}if(c.level===1)return 'Segment: '+c.sel['Customer[Segment]'];return 'All customers';}}
    ]
  });
})();
