"use strict";
/* Topic 10 - Time intelligence (complete). All challenges are graded by month (Date[YearMonth]) plus the grand total
   unless noTotal is set. Oracles work on epoch-day numbers: H.dateRange gives the visible dates, H.inRange sums a range. */
(function(){
  const REV=s=>s.Revenue;
  const range=(D,c)=>H.dateRange(D,c);                       // {min,max} of the dates visible in this row, or null
  const rev=(D,c,a,b)=>H.inRange(D,c,a,b,REV);                 // revenue between two epoch days, ignoring the row's Date filters
  // a whole-month period shifted by k months stays a whole-month period (DATEADD / SAMEPERIODLASTYEAR behaviour)
  const shifted=(r,k)=>({min:H.som(H.shiftMonths(r.min,k)),max:H.eom(H.shiftMonths(r.max,k))});

  registerTopic({
    id:'T10',title:'Time intelligence',order:10,
    concept:[
      'Time intelligence needs a proper date table: here `Date` is marked as the date table and `Date[Date]` is a real date column. Always pass `Date[Date]` (never `Shipment[DateKey]` or `Date[DateKey]`). Functions such as `DATESYTD`, `SAMEPERIODLASTYEAR`, `DATEADD` and `DATESINPERIOD` return a table of dates that you give to `CALCULATE` as a filter. A filter on `Date[Date]` replaces the other filters on the Date table, so the month of the visual row is swapped for the new date range.',
      '',
      '  Revenue YTD = CALCULATE([Total Revenue], DATESYTD(Date[Date]))',
      '  Revenue PY = CALCULATE([Total Revenue], SAMEPERIODLASTYEAR(Date[Date]))',
      '  Fiscal YTD = TOTALYTD([Total Revenue], Date[Date], "09-30")',
      '',
      'The fiscal year starts on 1 October, so its year-end argument is "09-30". Compare dates with dates: Date[Date] against DATE(2025,1,1) or MAX(Date[Date]). Comparing an int DateKey with a Date is an error.'
    ].join('\n'),
    challenges:[
      {id:'T10-01',level:'Beginner',title:'Revenue year-to-date',by:['Date[YearMonth]'],checks:['slash','unqual','hardcodedPeriod'],
       prompt:'Year-to-date revenue for the calendar year: revenue from 1 January up to the last date of the current period. It is shown by month, so March shows January to March.',
       hint:'TOTALYTD(expression, Date[Date]) does it in one function. DATESYTD(Date[Date]) inside CALCULATE is the long form.',
       ref:'TOTALYTD([Total Revenue], Date[Date])',
       alts:[{code:'CALCULATE([Total Revenue], DATESYTD(Date[Date]))'},{code:'CALCULATE(SUM(Shipment[Revenue]), DATESYTD(Date[Date]))'}],
       wrongs:[{code:'[Total Revenue]'},{code:'CALCULATE([Total Revenue], DATESMTD(Date[Date]))'},{code:'CALCULATE([Total Revenue], Date[Year] = 2025)',warn:'hardcodedPeriod'}],
       why:'DATESYTD returns every date from 1 January to the last date in the current context. CALCULATE uses that table as the filter on Date[Date] and drops the single-month filter of the row, so each month accumulates.',
       oracle:(D,c)=>{const r=range(D,c);return r?rev(D,c,H.yearStart(r.max),r.max):null;}},
      {id:'T10-02',level:'Intermediate',title:'Quarter-to-date revenue',by:['Date[YearMonth]'],checks:['slash','unqual','hardcodedPeriod'],
       prompt:'Quarter-to-date revenue: revenue from the first day of the calendar quarter up to the last date of the current period. May shows April to May, June shows April to June.',
       hint:'The quarter version of TOTALYTD is TOTALQTD; the filter function is DATESQTD.',
       ref:'TOTALQTD([Total Revenue], Date[Date])',
       alts:[{code:'CALCULATE([Total Revenue], DATESQTD(Date[Date]))'}],
       wrongs:[{code:'TOTALYTD([Total Revenue], Date[Date])'},{code:'[Total Revenue]'}],
       why:'DATESQTD starts at the first day of the quarter that contains the last visible date. In the first month of a quarter it equals the month; in the third month it covers three.',
       oracle:(D,c)=>{const r=range(D,c);return r?rev(D,c,H.sq(r.max),r.max):null;}},
      {id:'T10-03',level:'Intermediate',title:'Fiscal year-to-date (FY starts 1 Oct)',by:['Date[YearMonth]'],checks:['slash','unqual','hardcodedPeriod'],
       prompt:'Fiscal year-to-date revenue. The fiscal year starts on 1 October (Oct 2025 to Sep 2026 is FY2026). October shows only October; September shows the whole fiscal year.',
       hint:'TOTALYTD and DATESYTD take an optional year-end date as text in "MM-DD" form. The year ends on 30 September.',
       ref:'TOTALYTD([Total Revenue], Date[Date], "09-30")',
       alts:[{code:'CALCULATE([Total Revenue], DATESYTD(Date[Date], "09-30"))'},
             {code:'CALCULATE([Total Revenue], FILTER(ALL(Date), Date[FiscalYear] = MAX(Date[FiscalYear]) && Date[Date] <= MAX(Date[Date])))'}],
       wrongs:[{code:'TOTALYTD([Total Revenue], Date[Date])'},{code:'CALCULATE([Total Revenue], FILTER(ALL(Date), Date[FiscalYear] = MAX(Date[FiscalYear])))'},{code:'CALCULATE([Total Revenue], Date[FiscalYear] = 2026)',warn:'hardcodedPeriod'}],
       why:'The second argument of DATESYTD is the last day of the year. With "09-30" the year-to-date range restarts on 1 October, which is why October and November pick up only the new fiscal year and not the previous calendar months.',
       oracle:(D,c)=>{const r=range(D,c);return r?rev(D,c,H.yearStart(r.max,'09-30'),r.max):null;}},
      {id:'T10-04',level:'Intermediate',title:'Previous month revenue',by:['Date[YearMonth]'],noTotal:true,checks:['slash','unqual','hardcodedPeriod'],
       prompt:'Revenue of the previous calendar month, shown by month (March shows February). The grand total row is not graded for this one.',
       hint:'PREVIOUSMONTH(Date[Date]) is a filter table of the month before the first visible date. DATEADD(Date[Date], -1, MONTH) shifts the visible dates instead.',
       ref:'CALCULATE([Total Revenue], PREVIOUSMONTH(Date[Date]))',
       alts:[{code:'CALCULATE([Total Revenue], DATEADD(Date[Date], -1, MONTH))'},{code:'CALCULATE([Total Revenue], PARALLELPERIOD(Date[Date], -1, MONTH))'}],
       wrongs:[{code:'[Total Revenue]'},{code:'CALCULATE([Total Revenue], DATEADD(Date[Date], -30, DAY))'},{code:'CALCULATE([Total Revenue], DATEADD(Date[Date], -1, YEAR))'}],
       why:'All three forms move a whole-month selection back one month. Subtracting 30 days is not the same thing: months have 28 to 31 days, so the window slides off the month boundaries.',
       oracle:(D,c)=>{const r=range(D,c);if(!r)return null;const p=shifted(r,-1);return rev(D,c,p.min,p.max);}},
      {id:'T10-05',level:'Intermediate',title:'Same period last year',by:['Date[YearMonth]'],checks:['slash','unqual','hardcodedPeriod'],
       prompt:'Revenue for the same period one year earlier: March 2025 shows March 2024. The first year of data has no prior year, so it stays BLANK.',
       hint:'SAMEPERIODLASTYEAR(Date[Date]) is a filter table; DATEADD(Date[Date], -1, YEAR) is the general form.',
       ref:'CALCULATE([Total Revenue], SAMEPERIODLASTYEAR(Date[Date]))',
       alts:[{code:'CALCULATE([Total Revenue], DATEADD(Date[Date], -1, YEAR))'},{code:'CALCULATE([Total Revenue], PARALLELPERIOD(Date[Date], -12, MONTH))'},{code:'CALCULATE([Total Revenue], DATEADD(Date[Date], -12, MONTH))'}],
       wrongs:[{code:'CALCULATE([Total Revenue], Date[Year] = 2025)',warn:'hardcodedPeriod'},{code:'CALCULATE([Total Revenue], DATEADD(Date[Date], -1, MONTH))'},{code:'[Total Revenue]'}],
       why:'SAMEPERIODLASTYEAR shifts the visible dates back 12 months. Dates before the start of the date table do not exist, so 2024 months have nothing to look at and return BLANK.',
       oracle:(D,c)=>{const r=range(D,c);if(!r)return null;const p=shifted(r,-12);return rev(D,c,p.min,p.max);}},
      {id:'T10-06',level:'Pro',title:'Year-over-year growth %',by:['Date[YearMonth]'],checks:['slash','unqual','hardcodedPeriod','varRepeat'],
       prompt:'Year-over-year growth %: (revenue - revenue in the same period last year) / revenue in the same period last year. Show BLANK, not -100%, where there is no prior-year revenue (the whole first year).',
       hint:'Store the prior-year revenue in a VAR. DIVIDE returns BLANK when the denominator is BLANK, and IF(NOT(ISBLANK(...)), ...) makes the intent explicit.',
       ref:'VAR Cur = [Total Revenue]\nVAR PY = CALCULATE([Total Revenue], SAMEPERIODLASTYEAR(Date[Date]))\nRETURN\n    IF(NOT(ISBLANK(PY)), DIVIDE(Cur - PY, PY))',
       alts:[{code:'VAR PY = CALCULATE([Total Revenue], SAMEPERIODLASTYEAR(Date[Date]))\nRETURN DIVIDE([Total Revenue] - PY, PY)'},
             {code:'VAR PY = CALCULATE([Total Revenue], DATEADD(Date[Date], -1, YEAR))\nRETURN IF(ISBLANK(PY), BLANK(), DIVIDE([Total Revenue], PY) - 1)'}],
       wrongs:[{code:'VAR PY = CALCULATE([Total Revenue], SAMEPERIODLASTYEAR(Date[Date]))\nRETURN DIVIDE([Total Revenue], PY) - 1'},
               {code:'[Total Revenue] - CALCULATE([Total Revenue], SAMEPERIODLASTYEAR(Date[Date]))'},
               {code:'VAR PY = CALCULATE([Total Revenue], DATEADD(Date[Date], -1, MONTH))\nRETURN IF(NOT(ISBLANK(PY)), DIVIDE([Total Revenue] - PY, PY))'}],
       why:'In the first year PY is BLANK. DIVIDE(Cur, PY) is then BLANK, but BLANK - 1 is -1, so the naive "ratio minus 1" shows -100% for every 2024 month. Dividing the difference by PY, or checking ISBLANK(PY) first, keeps the first year empty.',
       oracle:(D,c)=>{const r=range(D,c);if(!r)return null;const p=shifted(r,-12);const py=rev(D,c,p.min,p.max);if(py==null||py===0)return null;const cur=rev(D,c,r.min,r.max)||0;return (cur-py)/py;}},
      {id:'T10-07',level:'Pro',title:'Rolling 3-month revenue',by:['Date[YearMonth]'],checks:['slash','unqual','hardcodedPeriod','varRepeat'],
       prompt:'Rolling 3-month revenue: the current month and the two months before it. May shows March to May. The first months of the data simply sum the months that exist.',
       hint:'DATESINPERIOD(Date[Date], <last date>, -3, MONTH) returns the three months that end at the last visible date. MAX(Date[Date]) gives that last date.',
       ref:'CALCULATE([Total Revenue], DATESINPERIOD(Date[Date], MAX(Date[Date]), -3, MONTH))',
       alts:[{code:'VAR LastDate = MAX(Date[Date])\nRETURN CALCULATE([Total Revenue], DATESINPERIOD(Date[Date], LastDate, -3, MONTH))'},
             {code:'CALCULATE([Total Revenue], DATESBETWEEN(Date[Date], EOMONTH(MAX(Date[Date]), -3) + 1, MAX(Date[Date])))'}],
       wrongs:[{code:'CALCULATE([Total Revenue], DATESINPERIOD(Date[Date], MAX(Date[Date]), -2, MONTH))'},
               {code:'CALCULATE([Total Revenue], DATESINPERIOD(Date[Date], MAX(Date[Date]), -90, DAY))'},
               {code:'CALCULATE([Total Revenue], DATEADD(Date[Date], -3, MONTH))'}],
       why:'DATESINPERIOD walks back from the last visible date, so every row gets a window that ends at its own month end. A window of -90 days slides off the month boundaries, and DATEADD(-3 MONTH) would shift the month instead of widening it.',
       oracle:(D,c)=>{const r=range(D,c);if(!r)return null;const e=r.max;const lo=(e===H.eom(e)?H.eom(H.shiftMonths(e,-3)):H.shiftMonths(e,-3))+1;return rev(D,c,lo,e);}},
      {id:'T10-08',level:'Pro',title:'Running total (all-time cumulative)',by:['Date[YearMonth]'],checks:['slash','unqual','hardcodedPeriod'],
       prompt:'Cumulative revenue from the very first date in the data up to the last date of the current period.',
       hint:'Filter the whole date table (ALL), keeping the dates that are not later than the last visible one: Date[Date] <= MAX(Date[Date]). MAX is evaluated before ALL removes the month filter, so use it inside the FILTER condition.',
       ref:'CALCULATE([Total Revenue], FILTER(ALL(Date), Date[Date] <= MAX(Date[Date])))',
       alts:[{code:'CALCULATE([Total Revenue], FILTER(ALL(Date[Date]), Date[Date] <= MAX(Date[Date])))'},
             {code:'CALCULATE([Total Revenue], DATESBETWEEN(Date[Date], BLANK(), MAX(Date[Date])))'},
             {code:'VAR LastDate = MAX(Date[Date])\nRETURN CALCULATE([Total Revenue], FILTER(ALL(Date), Date[Date] <= LastDate))'}],
       wrongs:[{code:'CALCULATE([Total Revenue], FILTER(ALL(Date), Date[Date] < MAX(Date[Date])))'},
               {code:'CALCULATE([Total Revenue], FILTER(Date, Date[Date] <= MAX(Date[Date])))'},
               {code:'TOTALYTD([Total Revenue], Date[Date])'}],
       why:'FILTER(ALL(Date), ...) looks at every date, not just the ones the row shows, and keeps those up to the row\'s last date. FILTER(Date, ...) only sees the dates already visible in the row, so it never reaches back.',
       oracle:(D,c)=>{const r=range(D,c);return r?rev(D,c,-1e9,r.max):null;}},
      {id:'T10-09',level:'Pro',title:'YTD growth vs last year\'s YTD',by:['Date[YearMonth]'],checks:['slash','unqual','hardcodedPeriod','varRepeat'],
       prompt:'Compare the year-to-date revenue with the year-to-date revenue at the same point last year, as a percentage: (YTD - last year\'s YTD) / last year\'s YTD. BLANK where last year has no data.',
       hint:'Two VARs: this year\'s TOTALYTD, and CALCULATE(TOTALYTD(...), SAMEPERIODLASTYEAR(Date[Date])) which computes the YTD of the shifted period. Then a blank-safe DIVIDE.',
       ref:'VAR YtdNow = TOTALYTD([Total Revenue], Date[Date])\nVAR YtdPY = CALCULATE(TOTALYTD([Total Revenue], Date[Date]), SAMEPERIODLASTYEAR(Date[Date]))\nRETURN\n    IF(NOT(ISBLANK(YtdPY)), DIVIDE(YtdNow - YtdPY, YtdPY))',
       alts:[{code:'VAR YtdNow = CALCULATE([Total Revenue], DATESYTD(Date[Date]))\nVAR YtdPY = CALCULATE([Total Revenue], DATESYTD(SAMEPERIODLASTYEAR(Date[Date])))\nRETURN DIVIDE(YtdNow - YtdPY, YtdPY)'}],
       wrongs:[{code:'VAR YtdNow = TOTALYTD([Total Revenue], Date[Date])\nVAR YtdPY = CALCULATE(TOTALYTD([Total Revenue], Date[Date]), SAMEPERIODLASTYEAR(Date[Date]))\nRETURN DIVIDE(YtdNow, YtdPY) - 1'},
               {code:'VAR YtdNow = TOTALYTD([Total Revenue], Date[Date])\nVAR PYMonth = CALCULATE([Total Revenue], SAMEPERIODLASTYEAR(Date[Date]))\nRETURN IF(NOT(ISBLANK(PYMonth)), DIVIDE(YtdNow - PYMonth, PYMonth))'},
               {code:'VAR Cur = [Total Revenue]\nVAR PY = CALCULATE([Total Revenue], SAMEPERIODLASTYEAR(Date[Date]))\nRETURN IF(NOT(ISBLANK(PY)), DIVIDE(Cur - PY, PY))'}],
       why:'The prior-year YTD is the YTD measure evaluated in the shifted period: CALCULATE moves the dates back a year first, and TOTALYTD inside then accumulates up to that earlier date. Comparing a YTD with a single month, or skipping the blank check, gives wrong numbers.',
       oracle:(D,c)=>{const r=range(D,c);if(!r)return null;const p=shifted(r,-12);const py=rev(D,c,H.yearStart(p.max),p.max);if(py==null||py===0)return null;const cur=rev(D,c,H.yearStart(r.max),r.max)||0;return (cur-py)/py;}},
      {id:'T10-10',level:'Pro',title:'Revenue by delivery date (USERELATIONSHIP)',by:['Date[YearMonth]'],checks:['slash','unqual'],
       prompt:'Revenue by DELIVERY month: each shipment counts in the month of its DeliveryDateKey instead of the month of its order date. The relationship Shipment[DeliveryDateKey] to Date[DateKey] exists but is inactive.',
       hint:'CALCULATE(expression, USERELATIONSHIP(Shipment[DeliveryDateKey], Date[DateKey])) switches the active relationship for that calculation only.',
       ref:'CALCULATE([Total Revenue], USERELATIONSHIP(Shipment[DeliveryDateKey], Date[DateKey]))',
       alts:[{code:'CALCULATE(SUM(Shipment[Revenue]), USERELATIONSHIP(Shipment[DeliveryDateKey], Date[DateKey]))'},{code:'CALCULATE([Total Revenue], USERELATIONSHIP(Date[DateKey], Shipment[DeliveryDateKey]))'}],
       wrongs:[{code:'[Total Revenue]'},{code:'CALCULATE([Total Revenue], USERELATIONSHIP(Shipment[DateKey], Date[DateKey]))'},{code:'CALCULATE([Total Revenue], DATEADD(Date[Date], 1, MONTH))'}],
       why:'Only one relationship between two tables can be active. USERELATIONSHIP activates the inactive one inside CALCULATE, so the month filter of the row now selects shipments by delivery date. Do not try to filter Shipment[DeliveryDateKey] against Date[Date]: an int key and a Date are different types.',
       oracle:(D,c)=>H.sumOrNull(H.vis(D,c,{dateField:'DeliveryDateKey'}),REV)}
    ]
  });
})();
