name: Live Feed

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"

permissions:
  contents: write

jobs:
  live-feed:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r Meridian-Logistics-Analytics/01_generator/requirements.txt

      - name: Run live feed
        working-directory: Meridian-Logistics-Analytics/01_generator
        run: |
          python live_feed.py

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add Meridian-Logistics-Analytics/02_data/raw/
          git add Meridian-Logistics-Analytics/02_data/_state/watermark.json

          git diff --cached --quiet || git commit -m "Daily live feed update"
          git push
